// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ClusterBackupConfig {
    /**
     * Indicates whether backups are enabled. If set to false, no backups will be created.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The frequency of backups in minutes.  Valid values are [5, 10, 15, 30, 60, 240, 1440]
     */
    frequencyMinutes?: pulumi.Input<number | undefined>;
    /**
     * The number of days to retain backups for.  Valid values are [2, 7, 30, 90, 365]. Can only be set once, further changes require opening a support ticket. See Updating backup retention for more information.
     */
    retentionDays?: pulumi.Input<number | undefined>;
}

export interface ClusterCustomerCloudAccount {
    aws?: pulumi.Input<inputs.ClusterCustomerCloudAccountAws | undefined>;
    azure?: pulumi.Input<inputs.ClusterCustomerCloudAccountAzure | undefined>;
    gcp?: pulumi.Input<inputs.ClusterCustomerCloudAccountGcp | undefined>;
}

export interface ClusterCustomerCloudAccountAws {
    /**
     * The AWS IAM Role ARN that CockroachDB Cloud will assume in your account.
     */
    arn: pulumi.Input<string>;
}

export interface ClusterCustomerCloudAccountAzure {
    /**
     * The Azure subscription ID in the customer-owned tenant.
     */
    subscriptionId: pulumi.Input<string>;
    /**
     * The customer-owned Azure tenant ID that contains the subscription.
     */
    tenantId: pulumi.Input<string>;
}

export interface ClusterCustomerCloudAccountGcp {
    /**
     * The customer-owned GCP service account email CockroachDB Cloud will impersonate.
     */
    serviceAccountEmail: pulumi.Input<string>;
}

export interface ClusterDedicated {
    /**
     * The IPv4 range in CIDR format that will be used by the cluster. This is supported only on GCP, and must have a subnet mask no larger than /19. Defaults to "172.28.0.0/14". This cannot be changed after cluster creation.
     */
    cidrRange?: pulumi.Input<string | undefined>;
    /**
     * Number of disk I/O operations per second that are permitted on each node in the cluster. Only configurable for AWS clusters during creation. For GCP and Azure clusters, this value is ignored and the cloud provider default is used. Omit this attribute to use the server-side default based on machine type and storage size. The provisioned value may differ from the requested value.
     */
    diskIops?: pulumi.Input<number | undefined>;
    /**
     * Machine type identifier within the given cloud provider, e.g., m6.xlarge, n2-standard-4. This attribute requires a feature flag to be enabled. It is recommended to leave this empty and use `numVirtualCpus` to control the machine type.
     */
    machineType?: pulumi.Input<string | undefined>;
    /**
     * Memory per node in GiB.
     */
    memoryGib?: pulumi.Input<number | undefined>;
    /**
     * Number of virtual CPUs per node in the cluster.
     */
    numVirtualCpus?: pulumi.Input<number | undefined>;
    /**
     * Set to true to assign private IP addresses to nodes. Required for CMEK and other advanced networking features. Clusters created with this flag will have advanced security features enabled.  This cannot be changed after cluster creation and incurs additional charges.  See [Create an Advanced Cluster](https://www.cockroachlabs.com/docs/cockroachcloud/create-an-advanced-cluster.html#step-6-configure-advanced-security-features) and [Pricing](https://www.cockroachlabs.com/pricing/) for more information.
     */
    privateNetworkVisibility?: pulumi.Input<boolean | undefined>;
    /**
     * Storage amount per node in GiB.
     */
    storageGib?: pulumi.Input<number | undefined>;
    /**
     * supports_cluster_virtualization specifies whether an Advanced cluster is started with a virtual cluster architecture. This field is restricted to Private Preview usage; see our documentation for details: https://www.cockroachlabs.com/docs/stable/cluster-virtualization-overview
     */
    supportsClusterVirtualization?: pulumi.Input<boolean | undefined>;
}

export interface ClusterRegion {
    /**
     * Internal DNS name of the cluster within the cloud provider's network. Used to connect to the cluster with PrivateLink or VPC peering.
     */
    internalDns?: pulumi.Input<string | undefined>;
    /**
     * Name of the region. Should match the region code used by the cluster's cloud provider.
     */
    name: pulumi.Input<string>;
    /**
     * Number of nodes in the region. Valid for Advanced clusters only.
     */
    nodeCount?: pulumi.Input<number | undefined>;
    /**
     * Set to true to mark this region as the primary for a serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
     */
    primary?: pulumi.Input<boolean | undefined>;
    /**
     * Domain name of the cluster for the private endpoint connection. This DNS name is used by GCP Private Service Connect to connect to the cluster.
     */
    privateEndpointDns?: pulumi.Input<string | undefined>;
    /**
     * The ID of the AWS S3 VPC gateway endpoint for this region. Used to configure S3 bucket policies that restrict access to traffic from this VPC endpoint. Only populated for Advanced clusters on AWS.
     */
    s3VpcEndpointId?: pulumi.Input<string | undefined>;
    /**
     * DNS name of the cluster's SQL interface. Used to connect to the cluster with IP allowlisting.
     */
    sqlDns?: pulumi.Input<string | undefined>;
    /**
     * DNS name used when connecting to the DB Console for the cluster.
     */
    uiDns?: pulumi.Input<string | undefined>;
}

export interface ClusterServerless {
    /**
     * Cluster identifier in a connection string.
     */
    routingId?: pulumi.Input<string | undefined>;
    /**
     * Spend limit in US cents.
     *
     * @deprecated The `spendLimit` attribute is deprecated and will be removed in a future release of the provider. Configure 'usage_limits' instead.
     */
    spendLimit?: pulumi.Input<number | undefined>;
    /**
     * Dictates the behavior of CockroachDB major version upgrades. Manual upgrades are not supported on CockroachDB Basic. Manual or automatic upgrades are supported on CockroachDB Standard. If you omit the field, it defaults to `AUTOMATIC`. Allowed values are:
     *   * MANUAL
     *   * AUTOMATIC
     */
    upgradeType?: pulumi.Input<string | undefined>;
    usageLimits?: pulumi.Input<inputs.ClusterServerlessUsageLimits | undefined>;
}

export interface ClusterServerlessUsageLimits {
    /**
     * Maximum number of vCPUs that the cluster can use.
     */
    provisionedVirtualCpus?: pulumi.Input<number | undefined>;
    /**
     * Maximum number of Request Units that the cluster can consume during the month.
     */
    requestUnitLimit?: pulumi.Input<number | undefined>;
    /**
     * Maximum amount of storage (in MiB) that the cluster can have at any time during the month.
     */
    storageMibLimit?: pulumi.Input<number | undefined>;
}

export interface CmekAdditionalRegion {
    /**
     * Internal DNS name of the cluster within the cloud provider's network. Used to connect to the cluster with PrivateLink or VPC peering.
     */
    internalDns?: pulumi.Input<string | undefined>;
    /**
     * Name of the region. Should match the region code used by the cluster's cloud provider.
     */
    name: pulumi.Input<string>;
    /**
     * Number of nodes in the region. Valid for Advanced clusters only.
     */
    nodeCount?: pulumi.Input<number | undefined>;
    /**
     * Set to true to mark this region as the primary for a serverless cluster. Exactly one region must be primary. Dedicated clusters expect to have no primary region.
     */
    primary?: pulumi.Input<boolean | undefined>;
    /**
     * Domain name of the cluster for the private endpoint connection. This DNS name is used by GCP Private Service Connect to connect to the cluster.
     */
    privateEndpointDns?: pulumi.Input<string | undefined>;
    /**
     * The ID of the AWS S3 VPC gateway endpoint for this region. Used to configure S3 bucket policies that restrict access to traffic from this VPC endpoint. Only populated for Advanced clusters on AWS.
     */
    s3VpcEndpointId?: pulumi.Input<string | undefined>;
    /**
     * DNS name of the cluster's SQL interface. Used to connect to the cluster with IP allowlisting.
     */
    sqlDns?: pulumi.Input<string | undefined>;
    /**
     * DNS name used when connecting to the DB Console for the cluster.
     */
    uiDns?: pulumi.Input<string | undefined>;
}

export interface CmekRegion {
    key: pulumi.Input<inputs.CmekRegionKey>;
    /**
     * Cloud provider region code.
     */
    region: pulumi.Input<string>;
    /**
     * Describes the status of the current encryption key within the region.
     */
    status?: pulumi.Input<string | undefined>;
}

export interface CmekRegionKey {
    /**
     * Principal to authenticate as in order to access the key.
     */
    authPrincipal: pulumi.Input<string>;
    /**
     * Indicates when the key was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Current status of this key.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Type of encryption key. Current allowed values are:
     *   * AWS_KMS
     *   * GCP_CLOUD_KMS
     *   * NULL_KMS
     *   * AZURE_KEY_VAULT
     */
    type: pulumi.Input<string>;
    /**
     * Indicates when the key was last updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Provider-specific URI pointing to the encryption key.
     */
    uri: pulumi.Input<string>;
    /**
     * Elaborates on the key's status and hints at how to fix issues that may have occurred during asynchronous key operations.
     */
    userMessage?: pulumi.Input<string | undefined>;
}

export interface JwtIssuerIdentityMap {
    /**
     * Specifies how to map the fetched token identity to an identity in CockroachDB Cloud. In case of a regular expression for token_identity, this must contain a \1 placeholder for the matched content. Note that you will need to escape the backslash in the string as in the example usage (\\1).
     */
    ccIdentity: pulumi.Input<string>;
    /**
     * Specifies how to fetch external identity from the token claim. A regular expression must start with a forward slash. The regular expression must be in RE2 compatible syntax. For further details, please see https://github.com/google/re2/wiki/Syntax.
     */
    tokenIdentity: pulumi.Input<string>;
}

export interface LogExportConfigGroup {
    /**
     * A list of CockroachDB log channels to include in this group.
     */
    channels: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the group, reflected in the log sink.
     */
    logName: pulumi.Input<string>;
    /**
     * The minimum log level to filter to this log group.
     */
    minLevel?: pulumi.Input<string | undefined>;
    /**
     * Governs whether this log group should aggregate redacted logs if unset.
     */
    redact?: pulumi.Input<boolean | undefined>;
}

export interface PrivateEndpointServicesService {
    /**
     * Availability Zone IDs of the private endpoint service. It is recommended, for cost optimization purposes, to create the private endpoint spanning these same availability zones. For more information, see data transfer cost information for your cloud provider.
     */
    availabilityZoneIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * @deprecated nested aws fields have been moved one level up. These fields will be removed in a future version
     */
    aws?: pulumi.Input<inputs.PrivateEndpointServicesServiceAws | undefined>;
    /**
     * Cloud provider associated with this service.
     */
    cloudProvider?: pulumi.Input<string | undefined>;
    /**
     * Server side ID of the private endpoint connection.
     */
    endpointServiceId?: pulumi.Input<string | undefined>;
    /**
     * Name of the endpoint service.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Cloud provider region code associated with this service.
     */
    regionName?: pulumi.Input<string | undefined>;
    /**
     * Operation status of the service.
     */
    status?: pulumi.Input<string | undefined>;
}

export interface PrivateEndpointServicesServiceAws {
    /**
     * AZ IDs users should create their VPCs in to minimize their cost.
     */
    availabilityZoneIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Server side ID of the PrivateLink connection.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * AWS service name used to create endpoints.
     */
    serviceName?: pulumi.Input<string | undefined>;
}

export interface PrivateEndpointServicesServicesMap {
    /**
     * Availability Zone IDs of the private endpoint service. It is recommended, for cost optimization purposes, to create the private endpoint spanning these same availability zones. For more information, see data transfer cost information for your cloud provider.
     */
    availabilityZoneIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * @deprecated nested aws fields have been moved one level up. These fields will be removed in a future version
     */
    aws?: pulumi.Input<inputs.PrivateEndpointServicesServicesMapAws | undefined>;
    /**
     * Cloud provider associated with this service.
     */
    cloudProvider?: pulumi.Input<string | undefined>;
    /**
     * Server side ID of the private endpoint connection.
     */
    endpointServiceId?: pulumi.Input<string | undefined>;
    /**
     * Name of the endpoint service.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Cloud provider region code associated with this service.
     */
    regionName?: pulumi.Input<string | undefined>;
    /**
     * Operation status of the service.
     */
    status?: pulumi.Input<string | undefined>;
}

export interface PrivateEndpointServicesServicesMapAws {
    /**
     * AZ IDs users should create their VPCs in to minimize their cost.
     */
    availabilityZoneIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Server side ID of the PrivateLink connection.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * AWS service name used to create endpoints.
     */
    serviceName?: pulumi.Input<string | undefined>;
}

export interface RestoreObject {
    /**
     * The database name in the fully qualified name of the objects to be restored. In the case of a job that restores `tpcc.public.warehouse`, this value would be `tpcc`.
     */
    database: pulumi.Input<string>;
    /**
     * The schema name in the fully qualified name of the objects to be restored. In the case of a job that restores `tpcc.public.warehouse`, this value would be `public`.
     */
    schema?: pulumi.Input<string | undefined>;
    /**
     * The table name in the fully qualified name of the objects to be restored. In the case of a job that restores `tpcc.public.warehouse`, this would value be `warehouse`.
     */
    tables?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface RestoreRestoreOpts {
    /**
     * Optionally specifies a target database to restore the table into during a table restore job. If not set, the table is restored into the database it belonged to in the source backup.
     */
    intoDb?: pulumi.Input<string | undefined>;
    /**
     * Optionally specifies the name of a new database to create as the target of a database restore job. If not set, the name defaults to the original database name from the source cluster.
     */
    newDbName?: pulumi.Input<string | undefined>;
    /**
     * If set, only the schema without any user data is restored.
     */
    schemaOnly?: pulumi.Input<boolean | undefined>;
    /**
     * Allows the restore job to continue in the event that there are mismatched localities between the backup and target cluster. Useful when restoring multi-region tables to a cluster missing some localities.
     */
    skipLocalitiesCheck?: pulumi.Input<boolean | undefined>;
    /**
     * Allows a table to be restored even if it has foreign key constraints referencing rows that no longer exist in the target cluster.
     */
    skipMissingForeignKeys?: pulumi.Input<boolean | undefined>;
    /**
     * Allows a table to be restored even if it contains a column whose `DEFAULT` value depends on a sequence. More information can be found [here](https://www.cockroachlabs.com/docs/stable/show-sequences).
     */
    skipMissingSequences?: pulumi.Input<boolean | undefined>;
    /**
     * Allows the job to skip restoring views that cannot be restored because their dependencies are not included in the current restore job.
     */
    skipMissingViews?: pulumi.Input<boolean | undefined>;
}

export interface UserRoleGrantRole {
    /**
     * ID of the resource. Required if the resourceType is 'FOLDER' or 'CLUSTER'. It should be omitted otherwise.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * Type of resource. Allowed values are:
     *   * ORGANIZATION
     *   * CLUSTER
     *   * FOLDER
     */
    resourceType: pulumi.Input<string>;
    /**
     * Name of the role to grant. Allowed values are:
     *   * BILLING_COORDINATOR
     *   * ORG_ADMIN
     *   * ORG_MEMBER
     *   * CLUSTER_ADMIN
     *   * CLUSTER_OPERATOR_WRITER
     *   * CLUSTER_DEVELOPER
     *   * CLUSTER_CREATOR
     *   * FOLDER_ADMIN
     *   * FOLDER_MOVER
     *   * METRICS_VIEWER
     *   * CLUSTER_MONITOR
     *   * BILLING_VIEWER
     */
    roleName: pulumi.Input<string>;
}

export interface UserRoleGrantsRole {
    /**
     * ID of the resource. Required if the resourceType is 'FOLDER' or 'CLUSTER'. It should be omitted otherwise.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * Type of resource. Allowed values are: 
     *   * ORGANIZATION
     *   * CLUSTER
     *   * FOLDER
     */
    resourceType: pulumi.Input<string>;
    /**
     * Name of the role to grant. Allowed values are:
     *   * BILLING_COORDINATOR
     *   * ORG_ADMIN
     *   * ORG_MEMBER
     *   * CLUSTER_ADMIN
     *   * CLUSTER_OPERATOR_WRITER
     *   * CLUSTER_DEVELOPER
     *   * CLUSTER_CREATOR
     *   * FOLDER_ADMIN
     *   * FOLDER_MOVER
     *   * METRICS_VIEWER
     *   * CLUSTER_MONITOR
     *   * BILLING_VIEWER
     */
    roleName: pulumi.Input<string>;
}
