// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Blackout windows schedule a period of up to 14 days for an ADVANCED cluster to block high-risk operations that impact SQL availability or require CRDB pod restarts.
 *
 * Two consecutive maintenance windows cannot be covered by blackout windows.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // This example assumes you already have an ADVANCED cluster and 
 * // an active maintenance window on that cluster.
 * const example = new cockroach.BlackoutWindow("example", {
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     startTime: "2025-03-15T09:00:00Z",
 *     endTime: "2025-03-18T09:00:00Z",
 * });
 * ```
 *
 * ## Import
 *
 * format : terraform import <resource> <cluster_id>:<blackout_window_id>
 *
 * ```sh
 * $ pulumi import cockroach:index/blackoutWindow:BlackoutWindow example d9bf7d1a-6e18-446a-cbd0-6a0aee8a9e18:ea131d23-1eg7-99f0-b79c-a42ee26r60re
 * ```
 */
export class BlackoutWindow extends pulumi.CustomResource {
    /**
     * Get an existing BlackoutWindow resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BlackoutWindowState, opts?: pulumi.CustomResourceOptions): BlackoutWindow {
        return new BlackoutWindow(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/blackoutWindow:BlackoutWindow';

    /**
     * Returns true if the given object is an instance of BlackoutWindow.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BlackoutWindow {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BlackoutWindow.__pulumiType;
    }

    /**
     * ID of the cluster the blackout window applies to.
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * The UTC end time for the blackout window in RFC3339 format (e.g. `2025-03-18T09:00:00Z`). Must fall within 14 days of `startTime` and no later than three months from now.
     */
    declare public readonly endTime: pulumi.Output<string>;
    /**
     * The UTC start time for the blackout window in RFC3339 format (e.g. `2025-03-15T09:00:00Z`). Must be scheduled at least seven days in advance.
     */
    declare public readonly startTime: pulumi.Output<string>;

    /**
     * Create a BlackoutWindow resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BlackoutWindowArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BlackoutWindowArgs | BlackoutWindowState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BlackoutWindowState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["endTime"] = state?.endTime;
            resourceInputs["startTime"] = state?.startTime;
        } else {
            const args = argsOrState as BlackoutWindowArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["endTime"] = args?.endTime;
            resourceInputs["startTime"] = args?.startTime;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BlackoutWindow.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BlackoutWindow resources.
 */
export interface BlackoutWindowState {
    /**
     * ID of the cluster the blackout window applies to.
     */
    clusterId?: pulumi.Input<string | undefined>;
    /**
     * The UTC end time for the blackout window in RFC3339 format (e.g. `2025-03-18T09:00:00Z`). Must fall within 14 days of `startTime` and no later than three months from now.
     */
    endTime?: pulumi.Input<string | undefined>;
    /**
     * The UTC start time for the blackout window in RFC3339 format (e.g. `2025-03-15T09:00:00Z`). Must be scheduled at least seven days in advance.
     */
    startTime?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a BlackoutWindow resource.
 */
export interface BlackoutWindowArgs {
    /**
     * ID of the cluster the blackout window applies to.
     */
    clusterId: pulumi.Input<string>;
    /**
     * The UTC end time for the blackout window in RFC3339 format (e.g. `2025-03-18T09:00:00Z`). Must fall within 14 days of `startTime` and no later than three months from now.
     */
    endTime?: pulumi.Input<string | undefined>;
    /**
     * The UTC start time for the blackout window in RFC3339 format (e.g. `2025-03-15T09:00:00Z`). Must be scheduled at least seven days in advance.
     */
    startTime?: pulumi.Input<string | undefined>;
}
