// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages client CA certs.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * // The X509 certificate in PEM format.
 * const clientCertificate = config.require("clientCertificate");
 * const prod = new cockroach.ClientCaCert("prod", {
 *     clientCaCertId: prodCockroachCluster.id,
 *     x509PemCert: clientCertificate,
 * });
 * ```
 *
 * ## Import
 *
 * format: <cluster id>
 *
 * ```sh
 * $ pulumi import cockroach:index/clientCaCert:ClientCaCert prod 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class ClientCaCert extends pulumi.CustomResource {
    /**
     * Get an existing ClientCaCert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClientCaCertState, opts?: pulumi.CustomResourceOptions): ClientCaCert {
        return new ClientCaCert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/clientCaCert:ClientCaCert';

    /**
     * Returns true if the given object is an instance of ClientCaCert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClientCaCert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClientCaCert.__pulumiType;
    }

    /**
     * Cluster ID.
     */
    declare public readonly clientCaCertId: pulumi.Output<string>;
    /**
     * Status of client CA certs on a cluster.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * X509 certificate in PEM format.
     */
    declare public readonly x509PemCert: pulumi.Output<string>;

    /**
     * Create a ClientCaCert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClientCaCertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClientCaCertArgs | ClientCaCertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClientCaCertState | undefined;
            resourceInputs["clientCaCertId"] = state?.clientCaCertId;
            resourceInputs["status"] = state?.status;
            resourceInputs["x509PemCert"] = state?.x509PemCert;
        } else {
            const args = argsOrState as ClientCaCertArgs | undefined;
            if (args?.clientCaCertId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientCaCertId'");
            }
            if (args?.x509PemCert === undefined && !opts.urn) {
                throw new Error("Missing required property 'x509PemCert'");
            }
            resourceInputs["clientCaCertId"] = args?.clientCaCertId;
            resourceInputs["x509PemCert"] = args?.x509PemCert;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClientCaCert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ClientCaCert resources.
 */
export interface ClientCaCertState {
    /**
     * Cluster ID.
     */
    clientCaCertId?: pulumi.Input<string | undefined>;
    /**
     * Status of client CA certs on a cluster.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * X509 certificate in PEM format.
     */
    x509PemCert?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ClientCaCert resource.
 */
export interface ClientCaCertArgs {
    /**
     * Cluster ID.
     */
    clientCaCertId: pulumi.Input<string>;
    /**
     * X509 certificate in PEM format.
     */
    x509PemCert: pulumi.Input<string>;
}
