// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * CockroachDB Cloud cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const advanced = new cockroach.Cluster("advanced", {
 *     name: "cockroach-advanced",
 *     cloudProvider: "GCP",
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: 15,
 *         numVirtualCpus: 4,
 *     },
 *     regions: [{
 *         name: "us-central1",
 *         nodeCount: 1,
 *     }],
 *     deleteProtection: true,
 *     backupConfig: {
 *         enabled: true,
 *         frequencyMinutes: 60,
 *         retentionDays: 30,
 *     },
 *     labels: {
 *         environment: "production",
 *         "cost-center": "mkt-1234",
 *     },
 * });
 * const standard = new cockroach.Cluster("standard", {
 *     name: "cockroach-standard",
 *     cloudProvider: "GCP",
 *     plan: "STANDARD",
 *     serverless: {
 *         usageLimits: {
 *             provisionedVirtualCpus: 2,
 *         },
 *         upgradeType: "AUTOMATIC",
 *     },
 *     regions: [{
 *         name: "us-east1",
 *     }],
 *     deleteProtection: false,
 *     backupConfig: {
 *         enabled: true,
 *         frequencyMinutes: 60,
 *         retentionDays: 30,
 *     },
 *     labels: {
 *         environment: "production",
 *         "cost-center": "hr-1234",
 *     },
 * });
 * const basic = new cockroach.Cluster("basic", {
 *     name: "cockroach-basic",
 *     cloudProvider: "GCP",
 *     plan: "BASIC",
 *     serverless: {},
 *     regions: [{
 *         name: "us-east1",
 *     }],
 *     deleteProtection: false,
 *     labels: {
 *         environment: "staging",
 *         "cost-center": "mkt-1234",
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * format: <cluster id>
 *
 * ```sh
 * $ pulumi import cockroach:index/cluster:Cluster my_cluster 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class Cluster extends pulumi.CustomResource {
    /**
     * Get an existing Cluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterState, opts?: pulumi.CustomResourceOptions): Cluster {
        return new Cluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/cluster:Cluster';

    /**
     * Returns true if the given object is an instance of Cluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cluster.__pulumiType;
    }

    /**
     * The cloud provider account ID that hosts the cluster. Needed for CMEK and other advanced features.
     */
    declare public /*out*/ readonly accountId: pulumi.Output<string>;
    /**
     * The backup settings for a cluster.
     *  Each cluster has backup settings that determine if backups are enabled, how frequently they are taken, and how long they are retained for. Use this attribute to manage those settings.
     */
    declare public readonly backupConfig: pulumi.Output<outputs.ClusterBackupConfig>;
    /**
     * Cloud provider used to host the cluster. Allowed values are:
     *   * GCP
     *   * AWS
     *   * AZURE
     */
    declare public readonly cloudProvider: pulumi.Output<string>;
    /**
     * The major version of CockroachDB running on the cluster. This value can be used to orchestrate version upgrades. Supported for ADVANCED and STANDARD clusters (when `serverless.upgrade_type` set to 'MANUAL'). (e.g. v25.0)
     */
    declare public readonly cockroachVersion: pulumi.Output<string>;
    /**
     * ID of the user who created the cluster.
     */
    declare public /*out*/ readonly creatorId: pulumi.Output<string>;
    /**
     * Cloud-specific details required to host the cluster in your own cloud account. Only one of `aws`, `gcp`, or `azure` may be specified. This feature is available in [Private Preview](https://www.cockroachlabs.com/docs/stable/cockroachdb-feature-availability). Contact your Cockroach Labs account team to enable this feature.
     */
    declare public readonly customerCloudAccount: pulumi.Output<outputs.ClusterCustomerCloudAccount | undefined>;
    declare public readonly dedicated: pulumi.Output<outputs.ClusterDedicated | undefined>;
    /**
     * Set to true to enable delete protection on the cluster. If unset, the server chooses the value on cluster creation, and preserves the value on cluster update.
     */
    declare public readonly deleteProtection: pulumi.Output<boolean>;
    /**
     * The full version string of CockroachDB running on the cluster. (e.g. v25.0.1)
     */
    declare public /*out*/ readonly fullVersion: pulumi.Output<string>;
    /**
     * Map of key-value pairs used to organize and categorize resources. If unset, labels will not be managed by Terraform. If set, labels defined in Terraform will overwrite any labels configured outside this platform.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string}>;
    /**
     * Name of the cluster.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Describes the current long-running operation, if any.
     */
    declare public /*out*/ readonly operationStatus: pulumi.Output<string>;
    /**
     * The ID of the cluster's parent folder. 'root' is used for a cluster at the root level.
     */
    declare public readonly parentId: pulumi.Output<string>;
    /**
     * Denotes cluster plan type: 'BASIC' or 'STANDARD' or 'ADVANCED'.
     */
    declare public readonly plan: pulumi.Output<string>;
    declare public readonly regions: pulumi.Output<outputs.ClusterRegion[]>;
    declare public readonly serverless: pulumi.Output<outputs.ClusterServerless | undefined>;
    /**
     * Describes whether the cluster is being created, updated, deleted, etc.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Describes the status of any in-progress CockroachDB upgrade or rollback.
     */
    declare public /*out*/ readonly upgradeStatus: pulumi.Output<string>;

    /**
     * Create a Cluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterArgs | ClusterState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["backupConfig"] = state?.backupConfig;
            resourceInputs["cloudProvider"] = state?.cloudProvider;
            resourceInputs["cockroachVersion"] = state?.cockroachVersion;
            resourceInputs["creatorId"] = state?.creatorId;
            resourceInputs["customerCloudAccount"] = state?.customerCloudAccount;
            resourceInputs["dedicated"] = state?.dedicated;
            resourceInputs["deleteProtection"] = state?.deleteProtection;
            resourceInputs["fullVersion"] = state?.fullVersion;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["operationStatus"] = state?.operationStatus;
            resourceInputs["parentId"] = state?.parentId;
            resourceInputs["plan"] = state?.plan;
            resourceInputs["regions"] = state?.regions;
            resourceInputs["serverless"] = state?.serverless;
            resourceInputs["state"] = state?.state;
            resourceInputs["upgradeStatus"] = state?.upgradeStatus;
        } else {
            const args = argsOrState as ClusterArgs | undefined;
            if (args?.cloudProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudProvider'");
            }
            if (args?.regions === undefined && !opts.urn) {
                throw new Error("Missing required property 'regions'");
            }
            resourceInputs["backupConfig"] = args?.backupConfig;
            resourceInputs["cloudProvider"] = args?.cloudProvider;
            resourceInputs["cockroachVersion"] = args?.cockroachVersion;
            resourceInputs["customerCloudAccount"] = args?.customerCloudAccount;
            resourceInputs["dedicated"] = args?.dedicated;
            resourceInputs["deleteProtection"] = args?.deleteProtection;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["parentId"] = args?.parentId;
            resourceInputs["plan"] = args?.plan;
            resourceInputs["regions"] = args?.regions;
            resourceInputs["serverless"] = args?.serverless;
            resourceInputs["accountId"] = undefined /*out*/;
            resourceInputs["creatorId"] = undefined /*out*/;
            resourceInputs["fullVersion"] = undefined /*out*/;
            resourceInputs["operationStatus"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["upgradeStatus"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cluster.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Cluster resources.
 */
export interface ClusterState {
    /**
     * The cloud provider account ID that hosts the cluster. Needed for CMEK and other advanced features.
     */
    accountId?: pulumi.Input<string | undefined>;
    /**
     * The backup settings for a cluster.
     *  Each cluster has backup settings that determine if backups are enabled, how frequently they are taken, and how long they are retained for. Use this attribute to manage those settings.
     */
    backupConfig?: pulumi.Input<inputs.ClusterBackupConfig | undefined>;
    /**
     * Cloud provider used to host the cluster. Allowed values are:
     *   * GCP
     *   * AWS
     *   * AZURE
     */
    cloudProvider?: pulumi.Input<string | undefined>;
    /**
     * The major version of CockroachDB running on the cluster. This value can be used to orchestrate version upgrades. Supported for ADVANCED and STANDARD clusters (when `serverless.upgrade_type` set to 'MANUAL'). (e.g. v25.0)
     */
    cockroachVersion?: pulumi.Input<string | undefined>;
    /**
     * ID of the user who created the cluster.
     */
    creatorId?: pulumi.Input<string | undefined>;
    /**
     * Cloud-specific details required to host the cluster in your own cloud account. Only one of `aws`, `gcp`, or `azure` may be specified. This feature is available in [Private Preview](https://www.cockroachlabs.com/docs/stable/cockroachdb-feature-availability). Contact your Cockroach Labs account team to enable this feature.
     */
    customerCloudAccount?: pulumi.Input<inputs.ClusterCustomerCloudAccount | undefined>;
    dedicated?: pulumi.Input<inputs.ClusterDedicated | undefined>;
    /**
     * Set to true to enable delete protection on the cluster. If unset, the server chooses the value on cluster creation, and preserves the value on cluster update.
     */
    deleteProtection?: pulumi.Input<boolean | undefined>;
    /**
     * The full version string of CockroachDB running on the cluster. (e.g. v25.0.1)
     */
    fullVersion?: pulumi.Input<string | undefined>;
    /**
     * Map of key-value pairs used to organize and categorize resources. If unset, labels will not be managed by Terraform. If set, labels defined in Terraform will overwrite any labels configured outside this platform.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Name of the cluster.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Describes the current long-running operation, if any.
     */
    operationStatus?: pulumi.Input<string | undefined>;
    /**
     * The ID of the cluster's parent folder. 'root' is used for a cluster at the root level.
     */
    parentId?: pulumi.Input<string | undefined>;
    /**
     * Denotes cluster plan type: 'BASIC' or 'STANDARD' or 'ADVANCED'.
     */
    plan?: pulumi.Input<string | undefined>;
    regions?: pulumi.Input<pulumi.Input<inputs.ClusterRegion>[] | undefined>;
    serverless?: pulumi.Input<inputs.ClusterServerless | undefined>;
    /**
     * Describes whether the cluster is being created, updated, deleted, etc.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * Describes the status of any in-progress CockroachDB upgrade or rollback.
     */
    upgradeStatus?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Cluster resource.
 */
export interface ClusterArgs {
    /**
     * The backup settings for a cluster.
     *  Each cluster has backup settings that determine if backups are enabled, how frequently they are taken, and how long they are retained for. Use this attribute to manage those settings.
     */
    backupConfig?: pulumi.Input<inputs.ClusterBackupConfig | undefined>;
    /**
     * Cloud provider used to host the cluster. Allowed values are:
     *   * GCP
     *   * AWS
     *   * AZURE
     */
    cloudProvider: pulumi.Input<string>;
    /**
     * The major version of CockroachDB running on the cluster. This value can be used to orchestrate version upgrades. Supported for ADVANCED and STANDARD clusters (when `serverless.upgrade_type` set to 'MANUAL'). (e.g. v25.0)
     */
    cockroachVersion?: pulumi.Input<string | undefined>;
    /**
     * Cloud-specific details required to host the cluster in your own cloud account. Only one of `aws`, `gcp`, or `azure` may be specified. This feature is available in [Private Preview](https://www.cockroachlabs.com/docs/stable/cockroachdb-feature-availability). Contact your Cockroach Labs account team to enable this feature.
     */
    customerCloudAccount?: pulumi.Input<inputs.ClusterCustomerCloudAccount | undefined>;
    dedicated?: pulumi.Input<inputs.ClusterDedicated | undefined>;
    /**
     * Set to true to enable delete protection on the cluster. If unset, the server chooses the value on cluster creation, and preserves the value on cluster update.
     */
    deleteProtection?: pulumi.Input<boolean | undefined>;
    /**
     * Map of key-value pairs used to organize and categorize resources. If unset, labels will not be managed by Terraform. If set, labels defined in Terraform will overwrite any labels configured outside this platform.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Name of the cluster.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the cluster's parent folder. 'root' is used for a cluster at the root level.
     */
    parentId?: pulumi.Input<string | undefined>;
    /**
     * Denotes cluster plan type: 'BASIC' or 'STANDARD' or 'ADVANCED'.
     */
    plan?: pulumi.Input<string | undefined>;
    regions: pulumi.Input<pulumi.Input<inputs.ClusterRegion>[]>;
    serverless?: pulumi.Input<inputs.ClusterServerless | undefined>;
}
