// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages the egress traffic policy for a CockroachDB Cloud cluster. When set to deny-by-default (allow_all = false), the cluster blocks all outbound traffic except to destinations explicitly allowed by egress rules (cockroach_egress_rule). When set to allow-all (allow_all = true), all outbound traffic is permitted and egress rules have no effect.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Example cluster
 * const myCluster = new cockroach.Cluster("my_cluster", {
 *     name: "my-advanced-cluster",
 *     cloudProvider: "AWS",
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: 15,
 *         numVirtualCpus: 4,
 *     },
 *     regions: [{
 *         name: "us-east-1",
 *         nodeCount: 1,
 *     }],
 * });
 * // Note: When using cockroach_egress_rule, the egress traffic policy is
 * // automatically set to deny-by-default. This resource is useful when you want to:
 * // 1. Explicitly manage the policy state
 * // 2. Block all outbound traffic without creating any egress rules
 * // 3. Reset the policy back to allow-all after removing egress rules
 * // Example: Manage egress traffic policy for a cluster
 * const outboundTraffic = new cockroach.EgressTrafficPolicy("outbound_traffic", {
 *     egressTrafficPolicyId: myCluster.id,
 *     allowAll: false,
 * });
 * export const egressPolicyClusterId = outboundTraffic.egressTrafficPolicyId;
 * export const egressPolicyAllowAll = outboundTraffic.allowAll;
 * ```
 *
 * ## Import
 *
 * format: <cluster_id>
 *
 * ```sh
 * $ pulumi import cockroach:index/egressTrafficPolicy:EgressTrafficPolicy outbound_traffic 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class EgressTrafficPolicy extends pulumi.CustomResource {
    /**
     * Get an existing EgressTrafficPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EgressTrafficPolicyState, opts?: pulumi.CustomResourceOptions): EgressTrafficPolicy {
        return new EgressTrafficPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/egressTrafficPolicy:EgressTrafficPolicy';

    /**
     * Returns true if the given object is an instance of EgressTrafficPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EgressTrafficPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EgressTrafficPolicy.__pulumiType;
    }

    /**
     * If true, all outbound connections from CockroachDB are allowed. If false, CockroachDB can only initiate network connections to destinations explicitly allowed by egress rules.
     */
    declare public readonly allowAll: pulumi.Output<boolean>;
    /**
     * Cluster ID.
     */
    declare public readonly egressTrafficPolicyId: pulumi.Output<string>;

    /**
     * Create a EgressTrafficPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EgressTrafficPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EgressTrafficPolicyArgs | EgressTrafficPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EgressTrafficPolicyState | undefined;
            resourceInputs["allowAll"] = state?.allowAll;
            resourceInputs["egressTrafficPolicyId"] = state?.egressTrafficPolicyId;
        } else {
            const args = argsOrState as EgressTrafficPolicyArgs | undefined;
            if (args?.allowAll === undefined && !opts.urn) {
                throw new Error("Missing required property 'allowAll'");
            }
            if (args?.egressTrafficPolicyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'egressTrafficPolicyId'");
            }
            resourceInputs["allowAll"] = args?.allowAll;
            resourceInputs["egressTrafficPolicyId"] = args?.egressTrafficPolicyId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EgressTrafficPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EgressTrafficPolicy resources.
 */
export interface EgressTrafficPolicyState {
    /**
     * If true, all outbound connections from CockroachDB are allowed. If false, CockroachDB can only initiate network connections to destinations explicitly allowed by egress rules.
     */
    allowAll?: pulumi.Input<boolean | undefined>;
    /**
     * Cluster ID.
     */
    egressTrafficPolicyId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EgressTrafficPolicy resource.
 */
export interface EgressTrafficPolicyArgs {
    /**
     * If true, all outbound connections from CockroachDB are allowed. If false, CockroachDB can only initiate network connections to destinations explicitly allowed by egress rules.
     */
    allowAll: pulumi.Input<boolean>;
    /**
     * Cluster ID.
     */
    egressTrafficPolicyId: pulumi.Input<string>;
}
