// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Egress rule for a CockroachDB Cloud cluster. Egress perimeter controls allow CockroachDB Cloud Advanced clusters to restrict outgoing traffic to a defined set of external destinations.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Example cluster (required for the examples above)
 * const myCluster = new cockroach.Cluster("my_cluster", {
 *     name: "my-advanced-cluster",
 *     cloudProvider: "AWS",
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: 15,
 *         numVirtualCpus: 4,
 *     },
 *     regions: [{
 *         name: "us-east-1",
 *         nodeCount: 1,
 *     }],
 * });
 * // Egress rules only take effect when the cluster's egress traffic policy is set
 * // to deny-by-default. When you create egress rules, the policy is automatically
 * // set to deny-by-default. Use cockroach_egress_traffic_policy to explicitly
 * // manage the policy state.
 * // Example: Allow egress to a specific FQDN on HTTPS port
 * const myEgressRule = new cockroach.EgressRule("my_egress_rule", {
 *     clusterId: myCluster.id,
 *     name: "external-api",
 *     description: "Allow outbound traffic to external API service",
 *     type: "FQDN",
 *     destination: "api.example.com",
 *     ports: [443],
 * });
 * // Example: Allow egress to a domain on multiple ports
 * const kafkaCluster = new cockroach.EgressRule("kafka_cluster", {
 *     clusterId: myCluster.id,
 *     name: "kafka-cluster",
 *     description: "Allow outbound traffic to Kafka brokers",
 *     type: "FQDN",
 *     destination: "kafka.internal.example.com",
 *     ports: [
 *         9092,
 *         9093,
 *         9094,
 *     ],
 * });
 * // Example: Allow egress to a CIDR range (all ports)
 * const internalNetwork = new cockroach.EgressRule("internal_network", {
 *     clusterId: myCluster.id,
 *     name: "internal-network",
 *     description: "Allow outbound traffic to internal network",
 *     type: "CIDR",
 *     destination: "10.0.0.0/8",
 * });
 * // Example: Allow egress to a specific IP on specific ports
 * const databaseServer = new cockroach.EgressRule("database_server", {
 *     clusterId: myCluster.id,
 *     name: "database-server",
 *     description: "Allow outbound traffic to external database",
 *     type: "CIDR",
 *     destination: "192.168.1.100/32",
 *     ports: [
 *         5432,
 *         3306,
 *     ],
 * });
 * export const myEgressRuleId = myEgressRule.id;
 * export const myEgressRuleState = myEgressRule.state;
 * ```
 *
 * ## Import
 *
 * format: <cluster_id>:<rule_id>
 *
 * ```sh
 * $ pulumi import cockroach:index/egressRule:EgressRule my_egress_rule 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:87654321-1234-5678-9abc-def012345678
 * ```
 */
export class EgressRule extends pulumi.CustomResource {
    /**
     * Get an existing EgressRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EgressRuleState, opts?: pulumi.CustomResourceOptions): EgressRule {
        return new EgressRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/egressRule:EgressRule';

    /**
     * Returns true if the given object is an instance of EgressRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EgressRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EgressRule.__pulumiType;
    }

    /**
     * ID of the cluster to which this egress rule applies.
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * Timestamp when the egress rule was created
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Indicates whether this egress rule is managed by CockroachDB Cloud services.
     */
    declare public /*out*/ readonly crlManaged: pulumi.Output<boolean>;
    /**
     * The intended purpose of egress to the destination.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Either a fully qualified domain name, for example www.cockroachlabs.com, or a CIDR range, for example, 123.45.67.89/32.
     */
    declare public readonly destination: pulumi.Output<string>;
    /**
     * A name for the rule.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * An array of allowed ports, for example [44,8080].
     */
    declare public readonly ports: pulumi.Output<number[] | undefined>;
    /**
     * Current state of the egress rule
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Whether the destination will be specified as a fully-qualified domain name (FQDN), or as a range of IP addresses specified in CIDR notation. Value is `FQDN` or `CIDR`.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a EgressRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EgressRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EgressRuleArgs | EgressRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EgressRuleState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["crlManaged"] = state?.crlManaged;
            resourceInputs["description"] = state?.description;
            resourceInputs["destination"] = state?.destination;
            resourceInputs["name"] = state?.name;
            resourceInputs["ports"] = state?.ports;
            resourceInputs["state"] = state?.state;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as EgressRuleArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.destination === undefined && !opts.urn) {
                throw new Error("Missing required property 'destination'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["description"] = args?.description;
            resourceInputs["destination"] = args?.destination;
            resourceInputs["name"] = args?.name;
            resourceInputs["ports"] = args?.ports;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["crlManaged"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EgressRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EgressRule resources.
 */
export interface EgressRuleState {
    /**
     * ID of the cluster to which this egress rule applies.
     */
    clusterId?: pulumi.Input<string | undefined>;
    /**
     * Timestamp when the egress rule was created
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Indicates whether this egress rule is managed by CockroachDB Cloud services.
     */
    crlManaged?: pulumi.Input<boolean | undefined>;
    /**
     * The intended purpose of egress to the destination.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Either a fully qualified domain name, for example www.cockroachlabs.com, or a CIDR range, for example, 123.45.67.89/32.
     */
    destination?: pulumi.Input<string | undefined>;
    /**
     * A name for the rule.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * An array of allowed ports, for example [44,8080].
     */
    ports?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    /**
     * Current state of the egress rule
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * Whether the destination will be specified as a fully-qualified domain name (FQDN), or as a range of IP addresses specified in CIDR notation. Value is `FQDN` or `CIDR`.
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EgressRule resource.
 */
export interface EgressRuleArgs {
    /**
     * ID of the cluster to which this egress rule applies.
     */
    clusterId: pulumi.Input<string>;
    /**
     * The intended purpose of egress to the destination.
     */
    description: pulumi.Input<string>;
    /**
     * Either a fully qualified domain name, for example www.cockroachlabs.com, or a CIDR range, for example, 123.45.67.89/32.
     */
    destination: pulumi.Input<string>;
    /**
     * A name for the rule.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * An array of allowed ports, for example [44,8080].
     */
    ports?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    /**
     * Whether the destination will be specified as a fully-qualified domain name (FQDN), or as a range of IP addresses specified in CIDR notation. Value is `FQDN` or `CIDR`.
     */
    type: pulumi.Input<string>;
}
