// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages custom domain names for an egress private endpoint in a CockroachDB Cloud cluster, in environments that require a custom name resolution to the endpointAddress of the endpoint.
 * - Terraform resource docs source
 * - [Cockroach Cloud docs](https://www.cockroachlabs.com/docs/cockroachcloud/egress-private-endpoints.html)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 * import * as confluent from "@pulumi/confluent";
 *
 * const myCluster = new cockroach.Cluster("my_cluster", {
 *     name: "my-cluster",
 *     cloudProvider: "AWS",
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: 15,
 *         numVirtualCpus: 4,
 *     },
 *     regions: [{
 *         name: "us-east-1",
 *         nodeCount: 1,
 *     }],
 * });
 * const basicEgressPrivateEndpoint = new cockroach.EgressPrivateEndpoint("basic", {
 *     clusterId: myCluster.id,
 *     region: "us-east-1",
 *     targetServiceType: "PRIVATE_SERVICE",
 *     targetServiceIdentifier: "com.amazonaws.vpce.us-east-1.vpce-svc-01234567890abcdef",
 * });
 * // Example: Basic usage with custom domain names
 * const basic = new cockroach.EgressPrivateEndpointDomainNames("basic", {
 *     clusterId: myCluster.id,
 *     endpointId: basicEgressPrivateEndpoint.id,
 *     domainNames: [
 *         "*.custom.domain",
 *         "another.domain",
 *     ],
 * });
 * const main = new confluent.index.Environment("main", {displayName: "main"});
 * const mainPrivateLinkAttachment = new confluent.index.PrivateLinkAttachment("main", {
 *     cloud: "AWS",
 *     region: "us-east-1",
 *     displayName: "main-private-link-attachment",
 *     environment: [{
 *         id: main.id,
 *     }],
 * });
 * const confluentCloudEgressPrivateEndpoint = new cockroach.EgressPrivateEndpoint("confluent_cloud", {
 *     clusterId: myCluster.id,
 *     region: "us-east-1",
 *     targetServiceType: "PRIVATE_SERVICE",
 *     targetServiceIdentifier: mainPrivateLinkAttachment.aws.vpcEndpointServiceName,
 * });
 * const cockroachCloud = new confluent.index.PrivateLinkAttachmentConnection("cockroach_cloud", {
 *     displayName: "cockroach-cloud-access-point",
 *     environment: [{
 *         id: main.id,
 *     }],
 *     aws: [{
 *         vpcEndpointId: confluentCloudEgressPrivateEndpoint.endpointConnectionId,
 *     }],
 *     privateLinkAttachment: [{
 *         id: mainPrivateLinkAttachment.id,
 *     }],
 * });
 * // Example: Usage when connecting to Confluent Cloud
 * const confluentCloud = new cockroach.EgressPrivateEndpointDomainNames("confluent_cloud", {
 *     clusterId: myCluster.id,
 *     endpointId: confluentCloudEgressPrivateEndpoint.id,
 *     domainNames: ["*.us-east-1.aws.private.confluent.cloud"],
 * }, {
 *     dependsOn: [cockroachCloud],
 * });
 * export const confluentCloudEgressPrivateEndpointDomains = {
 *     endpointId: confluentCloud.endpointId,
 *     clusterId: confluentCloud.clusterId,
 *     domainNames: confluentCloud.domainNames,
 * };
 * ```
 *
 * ## Import
 *
 * Import domain names for an egress private endpoint using cluster_id:endpoint_id format
 *
 * ```sh
 * $ pulumi import cockroach:index/egressPrivateEndpointDomainNames:EgressPrivateEndpointDomainNames basic 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:87654321-1234-5678-9abc-def012345678
 * ```
 */
export class EgressPrivateEndpointDomainNames extends pulumi.CustomResource {
    /**
     * Get an existing EgressPrivateEndpointDomainNames resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EgressPrivateEndpointDomainNamesState, opts?: pulumi.CustomResourceOptions): EgressPrivateEndpointDomainNames {
        return new EgressPrivateEndpointDomainNames(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/egressPrivateEndpointDomainNames:EgressPrivateEndpointDomainNames';

    /**
     * Returns true if the given object is an instance of EgressPrivateEndpointDomainNames.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EgressPrivateEndpointDomainNames {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EgressPrivateEndpointDomainNames.__pulumiType;
    }

    /**
     * cluster_id identifies the cluster to which this egress private endpoint applies
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * domain_names contains a list of domain names to associate with the egress private endpoint.
     */
    declare public readonly domainNames: pulumi.Output<string[]>;
    /**
     * endpoint_id is the `id` value of the egress private endpoint in CockroachDB Cloud.
     */
    declare public readonly endpointId: pulumi.Output<string>;

    /**
     * Create a EgressPrivateEndpointDomainNames resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EgressPrivateEndpointDomainNamesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EgressPrivateEndpointDomainNamesArgs | EgressPrivateEndpointDomainNamesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EgressPrivateEndpointDomainNamesState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["domainNames"] = state?.domainNames;
            resourceInputs["endpointId"] = state?.endpointId;
        } else {
            const args = argsOrState as EgressPrivateEndpointDomainNamesArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if (args?.domainNames === undefined && !opts.urn) {
                throw new Error("Missing required property 'domainNames'");
            }
            if (args?.endpointId === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpointId'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["domainNames"] = args?.domainNames;
            resourceInputs["endpointId"] = args?.endpointId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EgressPrivateEndpointDomainNames.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EgressPrivateEndpointDomainNames resources.
 */
export interface EgressPrivateEndpointDomainNamesState {
    /**
     * cluster_id identifies the cluster to which this egress private endpoint applies
     */
    clusterId?: pulumi.Input<string | undefined>;
    /**
     * domain_names contains a list of domain names to associate with the egress private endpoint.
     */
    domainNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * endpoint_id is the `id` value of the egress private endpoint in CockroachDB Cloud.
     */
    endpointId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EgressPrivateEndpointDomainNames resource.
 */
export interface EgressPrivateEndpointDomainNamesArgs {
    /**
     * cluster_id identifies the cluster to which this egress private endpoint applies
     */
    clusterId: pulumi.Input<string>;
    /**
     * domain_names contains a list of domain names to associate with the egress private endpoint.
     */
    domainNames: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * endpoint_id is the `id` value of the egress private endpoint in CockroachDB Cloud.
     */
    endpointId: pulumi.Input<string>;
}
