// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Egress private endpoint for a CockroachDB Cloud cluster. Egress private endpoints allow CockroachDB Cloud clusters to connect to external services through private network connections without traversing the public internet.
 * - Terraform resource docs source
 * - [Cockroach Cloud docs](https://www.cockroachlabs.com/docs/cockroachcloud/egress-private-endpoints.html)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Example clusters (required for the examples above)
 * const myAwsCluster = new cockroach.Cluster("my_aws_cluster", {
 *     name: "my-aws-cluster",
 *     cloudProvider: "AWS",
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: 15,
 *         numVirtualCpus: 4,
 *     },
 *     regions: [{
 *         name: "us-east-1",
 *         nodeCount: 1,
 *     }],
 * });
 * // Example: AWS endpoint for an application service
 * const awsAppService = new cockroach.EgressPrivateEndpoint("aws_app_service", {
 *     clusterId: myAwsCluster.id,
 *     region: "us-east-1",
 *     targetServiceType: "PRIVATE_SERVICE",
 *     targetServiceIdentifier: "com.amazonaws.vpce.us-east-1.vpce-svc-01234567890abcdef",
 * });
 * const myGcpCluster = new cockroach.Cluster("my_gcp_cluster", {
 *     name: "my-gcp-cluster",
 *     cloudProvider: "GCP",
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: 15,
 *         numVirtualCpus: 4,
 *     },
 *     regions: [{
 *         name: "us-east1",
 *         nodeCount: 1,
 *     }],
 * });
 * // Example: GCP endpoint for an application service
 * const gcpAppService = new cockroach.EgressPrivateEndpoint("gcp_app_service", {
 *     clusterId: myGcpCluster.id,
 *     region: "us-east1",
 *     targetServiceType: "PRIVATE_SERVICE",
 *     targetServiceIdentifier: "projects/project/regions/us-east1/serviceAttachments/0123456789abcdef",
 * });
 * // Example: AWS MSK with SASL/SCRAM authentication
 * const mskSaslScram = new cockroach.EgressPrivateEndpoint("msk_sasl_scram", {
 *     clusterId: myAwsCluster.id,
 *     region: "us-east-1",
 *     targetServiceType: "MSK_SASL_SCRAM",
 *     targetServiceIdentifier: "arn:aws:kafka:us-west-2:123456789012:cluster/my-cluster/12345678-1234-1234-1234-123456789012-2",
 * });
 * // Example: AWS MSK with IAM authentication
 * const mskIam = new cockroach.EgressPrivateEndpoint("msk_iam", {
 *     clusterId: myAwsCluster.id,
 *     region: "us-east-1",
 *     targetServiceType: "MSK_SASL_IAM",
 *     targetServiceIdentifier: "arn:aws:kafka:us-west-2:123456789012:cluster/my-iam-cluster/87654321-4321-4321-4321-210987654321-3",
 * });
 * // Example: AWS MSK with TLS authentication
 * const mskTls = new cockroach.EgressPrivateEndpoint("msk_tls", {
 *     clusterId: myAwsCluster.id,
 *     region: "us-east-1",
 *     targetServiceType: "MSK_TLS",
 *     targetServiceIdentifier: "arn:aws:kafka:eu-west-1:123456789012:cluster/my-tls-cluster/abcdef12-abcd-abcd-abcd-abcdef123456-4",
 * });
 * export const appServiceEndpointId = awsAppService.id;
 * export const appServiceEndpointAddress = awsAppService.endpointAddress;
 * export const appServiceConnectionId = awsAppService.endpointConnectionId;
 * export const mskEndpoints = {
 *     saslScram: {
 *         id: mskSaslScram.id,
 *         address: mskSaslScram.endpointAddress,
 *         state: mskSaslScram.state,
 *     },
 *     iam: {
 *         id: mskIam.id,
 *         address: mskIam.endpointAddress,
 *         state: mskIam.state,
 *     },
 *     tls: {
 *         id: mskTls.id,
 *         address: mskTls.endpointAddress,
 *         state: mskTls.state,
 *     },
 * };
 * ```
 *
 * ## Import
 *
 * Import an egress private endpoint using cluster_id:endpoint_id format
 *
 * ```sh
 * $ pulumi import cockroach:index/egressPrivateEndpoint:EgressPrivateEndpoint app_service 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:87654321-1234-5678-9abc-def012345678
 * ```
 *
 * Import multiple egress private endpoints
 *
 * ```sh
 * $ pulumi import cockroach:index/egressPrivateEndpoint:EgressPrivateEndpoint msk_sasl_scram 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:12345678-abcd-efgh-ijkl-mnopqrstuvwx
 * $ pulumi import cockroach:index/egressPrivateEndpoint:EgressPrivateEndpoint msk_iam 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:abcdef12-3456-7890-abcd-ef1234567890
 * $ pulumi import cockroach:index/egressPrivateEndpoint:EgressPrivateEndpoint msk_tls 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:fedcba98-7654-3210-fedc-ba9876543210
 * ```
 */
export class EgressPrivateEndpoint extends pulumi.CustomResource {
    /**
     * Get an existing EgressPrivateEndpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EgressPrivateEndpointState, opts?: pulumi.CustomResourceOptions): EgressPrivateEndpoint {
        return new EgressPrivateEndpoint(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/egressPrivateEndpoint:EgressPrivateEndpoint';

    /**
     * Returns true if the given object is an instance of EgressPrivateEndpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EgressPrivateEndpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EgressPrivateEndpoint.__pulumiType;
    }

    /**
     * cluster_id identifies the cluster to which this egress private endpoint applies
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * endpoint_address is the cloud-provider generated address (either IP address or DNS name) through which the endpoint is accessible
     */
    declare public /*out*/ readonly endpointAddress: pulumi.Output<string>;
    /**
     * endpoint_connection_id is the cloud service-specific ID for egress private endpoints. This connection ID is visible in CockroachDB and cloud service provider consoles as "VPC endpoint ID" and is used to uniquely identify the endpoint in external configurations
     */
    declare public /*out*/ readonly endpointConnectionId: pulumi.Output<string>;
    /**
     * region represents the region that the endpoint will be created in
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * state represents the current state of the endpoint. Potential values are:
     *   * PENDING
     *   * PENDING_ACCEPTANCE
     *   * AVAILABLE
     *   * DELETING
     *   * DELETED
     *   * REJECTED
     *   * FAILED
     *   * EXPIRED
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * target_service_identifier represents the identifier of the target service that the CockroachDB endpoint connects to. For example, this would be the Service Name for AWS, Service Attachment for GCP, or ARN for AWS MSK
     */
    declare public readonly targetServiceIdentifier: pulumi.Output<string>;
    /**
     * target_service_type represents the type of target service. Allowed values are:
     *   * PRIVATE_SERVICE
     *   * MSK_SASL_SCRAM
     *   * MSK_SASL_IAM
     *   * MSK_TLS
     */
    declare public readonly targetServiceType: pulumi.Output<string>;

    /**
     * Create a EgressPrivateEndpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EgressPrivateEndpointArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EgressPrivateEndpointArgs | EgressPrivateEndpointState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EgressPrivateEndpointState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["endpointAddress"] = state?.endpointAddress;
            resourceInputs["endpointConnectionId"] = state?.endpointConnectionId;
            resourceInputs["region"] = state?.region;
            resourceInputs["state"] = state?.state;
            resourceInputs["targetServiceIdentifier"] = state?.targetServiceIdentifier;
            resourceInputs["targetServiceType"] = state?.targetServiceType;
        } else {
            const args = argsOrState as EgressPrivateEndpointArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.targetServiceIdentifier === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetServiceIdentifier'");
            }
            if (args?.targetServiceType === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetServiceType'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["region"] = args?.region;
            resourceInputs["targetServiceIdentifier"] = args?.targetServiceIdentifier;
            resourceInputs["targetServiceType"] = args?.targetServiceType;
            resourceInputs["endpointAddress"] = undefined /*out*/;
            resourceInputs["endpointConnectionId"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EgressPrivateEndpoint.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EgressPrivateEndpoint resources.
 */
export interface EgressPrivateEndpointState {
    /**
     * cluster_id identifies the cluster to which this egress private endpoint applies
     */
    clusterId?: pulumi.Input<string | undefined>;
    /**
     * endpoint_address is the cloud-provider generated address (either IP address or DNS name) through which the endpoint is accessible
     */
    endpointAddress?: pulumi.Input<string | undefined>;
    /**
     * endpoint_connection_id is the cloud service-specific ID for egress private endpoints. This connection ID is visible in CockroachDB and cloud service provider consoles as "VPC endpoint ID" and is used to uniquely identify the endpoint in external configurations
     */
    endpointConnectionId?: pulumi.Input<string | undefined>;
    /**
     * region represents the region that the endpoint will be created in
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * state represents the current state of the endpoint. Potential values are:
     *   * PENDING
     *   * PENDING_ACCEPTANCE
     *   * AVAILABLE
     *   * DELETING
     *   * DELETED
     *   * REJECTED
     *   * FAILED
     *   * EXPIRED
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * target_service_identifier represents the identifier of the target service that the CockroachDB endpoint connects to. For example, this would be the Service Name for AWS, Service Attachment for GCP, or ARN for AWS MSK
     */
    targetServiceIdentifier?: pulumi.Input<string | undefined>;
    /**
     * target_service_type represents the type of target service. Allowed values are:
     *   * PRIVATE_SERVICE
     *   * MSK_SASL_SCRAM
     *   * MSK_SASL_IAM
     *   * MSK_TLS
     */
    targetServiceType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EgressPrivateEndpoint resource.
 */
export interface EgressPrivateEndpointArgs {
    /**
     * cluster_id identifies the cluster to which this egress private endpoint applies
     */
    clusterId: pulumi.Input<string>;
    /**
     * region represents the region that the endpoint will be created in
     */
    region: pulumi.Input<string>;
    /**
     * target_service_identifier represents the identifier of the target service that the CockroachDB endpoint connects to. For example, this would be the Service Name for AWS, Service Attachment for GCP, or ARN for AWS MSK
     */
    targetServiceIdentifier: pulumi.Input<string>;
    /**
     * target_service_type represents the type of target service. Allowed values are:
     *   * PRIVATE_SERVICE
     *   * MSK_SASL_SCRAM
     *   * MSK_SASL_IAM
     *   * MSK_TLS
     */
    targetServiceType: pulumi.Input<string>;
}
