// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Utility resource that represents the one-time action of finalizing a cluster's pending CockroachDB version upgrade.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const clusterId = config.require("clusterId");
 * const cockroachVersion = config.require("cockroachVersion");
 * const cockroach2 = new cockroach.FinalizeVersionUpgrade("cockroach", {
 *     finalizeVersionUpgradeId: clusterId,
 *     cockroachVersion: cockroachVersion,
 * });
 * ```
 */
export class FinalizeVersionUpgrade extends pulumi.CustomResource {
    /**
     * Get an existing FinalizeVersionUpgrade resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FinalizeVersionUpgradeState, opts?: pulumi.CustomResourceOptions): FinalizeVersionUpgrade {
        return new FinalizeVersionUpgrade(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/finalizeVersionUpgrade:FinalizeVersionUpgrade';

    /**
     * Returns true if the given object is an instance of FinalizeVersionUpgrade.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FinalizeVersionUpgrade {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FinalizeVersionUpgrade.__pulumiType;
    }

    /**
     * Major version of the cluster to be finalized.
     */
    declare public readonly cockroachVersion: pulumi.Output<string>;
    /**
     * Cluster ID.
     */
    declare public readonly finalizeVersionUpgradeId: pulumi.Output<string>;

    /**
     * Create a FinalizeVersionUpgrade resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FinalizeVersionUpgradeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FinalizeVersionUpgradeArgs | FinalizeVersionUpgradeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FinalizeVersionUpgradeState | undefined;
            resourceInputs["cockroachVersion"] = state?.cockroachVersion;
            resourceInputs["finalizeVersionUpgradeId"] = state?.finalizeVersionUpgradeId;
        } else {
            const args = argsOrState as FinalizeVersionUpgradeArgs | undefined;
            if (args?.cockroachVersion === undefined && !opts.urn) {
                throw new Error("Missing required property 'cockroachVersion'");
            }
            if (args?.finalizeVersionUpgradeId === undefined && !opts.urn) {
                throw new Error("Missing required property 'finalizeVersionUpgradeId'");
            }
            resourceInputs["cockroachVersion"] = args?.cockroachVersion;
            resourceInputs["finalizeVersionUpgradeId"] = args?.finalizeVersionUpgradeId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FinalizeVersionUpgrade.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FinalizeVersionUpgrade resources.
 */
export interface FinalizeVersionUpgradeState {
    /**
     * Major version of the cluster to be finalized.
     */
    cockroachVersion?: pulumi.Input<string | undefined>;
    /**
     * Cluster ID.
     */
    finalizeVersionUpgradeId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FinalizeVersionUpgrade resource.
 */
export interface FinalizeVersionUpgradeArgs {
    /**
     * Major version of the cluster to be finalized.
     */
    cockroachVersion: pulumi.Input<string>;
    /**
     * Cluster ID.
     */
    finalizeVersionUpgradeId: pulumi.Input<string>;
}
