// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Information about backups stored on a specific cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Fetch the latest backup
 * const latestBackup = cockroach.getBackups({
 *     clusterId: prodCluster.id,
 *     sortOrder: "DESC",
 *     limit: 1,
 * });
 * export const latestBackupId = latestBackup.then(latestBackup => latestBackup.backups?.[0]?.id);
 * // Fetch backups within a specific date range
 * const backupsInRange = cockroach.getBackups({
 *     clusterId: prodCluster.id,
 *     startTime: "2025-08-15",
 *     endTime: "2025-08-19",
 *     sortOrder: "DESC",
 *     limit: 5,
 * });
 * ```
 */
export function getBackups(args: GetBackupsArgs, opts?: pulumi.InvokeOptions): Promise<GetBackupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cockroach:index/getBackups:getBackups", {
        "clusterId": args.clusterId,
        "endTime": args.endTime,
        "limit": args.limit,
        "sortOrder": args.sortOrder,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsArgs {
    /**
     * The ID of the cluster containing the managed backups to be retrieved.
     */
    clusterId: string;
    /**
     * Ending timestamp of the range (exclusive) used to search for backups based on their restore point. If this field is provided, startTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    endTime?: string;
    /**
     * The maximum number of backups to return. If not set, only the first 500 backups will be returned.
     */
    limit?: number;
    /**
     * Specifies the sort direction for the returned results, which are ordered based on the `asOfTime` field. Use `ASC` for ascending or `DESC` for descending order.
     */
    sortOrder?: string;
    /**
     * Beginning timestamp of the range (inclusive) used to search for backups based on their restore point. If this field is provided, endTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    startTime?: string;
}

/**
 * A collection of values returned by getBackups.
 */
export interface GetBackupsResult {
    readonly backups: outputs.GetBackupsBackup[];
    /**
     * The ID of the cluster containing the managed backups to be retrieved.
     */
    readonly clusterId: string;
    /**
     * Ending timestamp of the range (exclusive) used to search for backups based on their restore point. If this field is provided, startTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    readonly endTime?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The maximum number of backups to return. If not set, only the first 500 backups will be returned.
     */
    readonly limit?: number;
    /**
     * Specifies the sort direction for the returned results, which are ordered based on the `asOfTime` field. Use `ASC` for ascending or `DESC` for descending order.
     */
    readonly sortOrder?: string;
    /**
     * Beginning timestamp of the range (inclusive) used to search for backups based on their restore point. If this field is provided, endTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    readonly startTime?: string;
}
/**
 * Information about backups stored on a specific cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Fetch the latest backup
 * const latestBackup = cockroach.getBackups({
 *     clusterId: prodCluster.id,
 *     sortOrder: "DESC",
 *     limit: 1,
 * });
 * export const latestBackupId = latestBackup.then(latestBackup => latestBackup.backups?.[0]?.id);
 * // Fetch backups within a specific date range
 * const backupsInRange = cockroach.getBackups({
 *     clusterId: prodCluster.id,
 *     startTime: "2025-08-15",
 *     endTime: "2025-08-19",
 *     sortOrder: "DESC",
 *     limit: 5,
 * });
 * ```
 */
export function getBackupsOutput(args: GetBackupsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBackupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cockroach:index/getBackups:getBackups", {
        "clusterId": args.clusterId,
        "endTime": args.endTime,
        "limit": args.limit,
        "sortOrder": args.sortOrder,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsOutputArgs {
    /**
     * The ID of the cluster containing the managed backups to be retrieved.
     */
    clusterId: pulumi.Input<string>;
    /**
     * Ending timestamp of the range (exclusive) used to search for backups based on their restore point. If this field is provided, startTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    endTime?: pulumi.Input<string | undefined>;
    /**
     * The maximum number of backups to return. If not set, only the first 500 backups will be returned.
     */
    limit?: pulumi.Input<number | undefined>;
    /**
     * Specifies the sort direction for the returned results, which are ordered based on the `asOfTime` field. Use `ASC` for ascending or `DESC` for descending order.
     */
    sortOrder?: pulumi.Input<string | undefined>;
    /**
     * Beginning timestamp of the range (inclusive) used to search for backups based on their restore point. If this field is provided, endTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    startTime?: pulumi.Input<string | undefined>;
}
