// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Retrieve blackout windows defined for a CockroachDB Cloud cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // List all blackout windows (upto 100)
 * const all = cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 * });
 * // Limit results and sort order 
 * const limited = cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     limit: 3,
 *     sortOrder: "DESC",
 * });
 * // Pagination: fetch page 1, and then use the token for page 2
 * const page1 = cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     limit: 2,
 * });
 * const page2 = page1.then(page1 => cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     page: page1.nextPage,
 * }));
 * ```
 */
export function getBlackoutWindows(args: GetBlackoutWindowsArgs, opts?: pulumi.InvokeOptions): Promise<GetBlackoutWindowsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cockroach:index/getBlackoutWindows:getBlackoutWindows", {
        "clusterId": args.clusterId,
        "limit": args.limit,
        "page": args.page,
        "sortOrder": args.sortOrder,
    }, opts);
}

/**
 * A collection of arguments for invoking getBlackoutWindows.
 */
export interface GetBlackoutWindowsArgs {
    /**
     * ID of the cluster to query for blackout windows.
     */
    clusterId: string;
    /**
     * Maximum number of blackout windows to return in a single response. Defaults to 100 when not set.
     */
    limit?: number;
    /**
     * A pagination token used to request the next page of results. This value should come from the `nextPage` attribute of a previous data source call.
     */
    page?: string;
    /**
     * Specifies the sort direction for the returned results, which are ordered based on the `startTime` field. Use `ASC` for ascending or `DESC` for descending order. Defaults to `ASC`.
     */
    sortOrder?: string;
}

/**
 * A collection of values returned by getBlackoutWindows.
 */
export interface GetBlackoutWindowsResult {
    /**
     * List of blackout windows returned by the API.
     */
    readonly blackoutWindows: outputs.GetBlackoutWindowsBlackoutWindow[];
    /**
     * ID of the cluster to query for blackout windows.
     */
    readonly clusterId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Maximum number of blackout windows to return in a single response. Defaults to 100 when not set.
     */
    readonly limit?: number;
    /**
     * Pagination token for the next page of results returned by the API. Pass this value into the `page` argument in a subsequent data source call to retrieve the next set of blackout windows. Empty if there are no more pages.
     */
    readonly nextPage: string;
    /**
     * A pagination token used to request the next page of results. This value should come from the `nextPage` attribute of a previous data source call.
     */
    readonly page?: string;
    /**
     * Specifies the sort direction for the returned results, which are ordered based on the `startTime` field. Use `ASC` for ascending or `DESC` for descending order. Defaults to `ASC`.
     */
    readonly sortOrder?: string;
}
/**
 * Retrieve blackout windows defined for a CockroachDB Cloud cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // List all blackout windows (upto 100)
 * const all = cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 * });
 * // Limit results and sort order 
 * const limited = cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     limit: 3,
 *     sortOrder: "DESC",
 * });
 * // Pagination: fetch page 1, and then use the token for page 2
 * const page1 = cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     limit: 2,
 * });
 * const page2 = page1.then(page1 => cockroach.getBlackoutWindows({
 *     clusterId: "123e4567-e89b-12d3-a456-426614174000",
 *     page: page1.nextPage,
 * }));
 * ```
 */
export function getBlackoutWindowsOutput(args: GetBlackoutWindowsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBlackoutWindowsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cockroach:index/getBlackoutWindows:getBlackoutWindows", {
        "clusterId": args.clusterId,
        "limit": args.limit,
        "page": args.page,
        "sortOrder": args.sortOrder,
    }, opts);
}

/**
 * A collection of arguments for invoking getBlackoutWindows.
 */
export interface GetBlackoutWindowsOutputArgs {
    /**
     * ID of the cluster to query for blackout windows.
     */
    clusterId: pulumi.Input<string>;
    /**
     * Maximum number of blackout windows to return in a single response. Defaults to 100 when not set.
     */
    limit?: pulumi.Input<number | undefined>;
    /**
     * A pagination token used to request the next page of results. This value should come from the `nextPage` attribute of a previous data source call.
     */
    page?: pulumi.Input<string | undefined>;
    /**
     * Specifies the sort direction for the returned results, which are ordered based on the `startTime` field. Use `ASC` for ascending or `DESC` for descending order. Defaults to `ASC`.
     */
    sortOrder?: pulumi.Input<string | undefined>;
}
