// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * CockroachDB Cloud cluster. Can be Dedicated or Serverless.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const clusterId = config.require("clusterId");
 * const cockroach2 = cockroach.getCluster({
 *     id: clusterId,
 * });
 * ```
 */
export function getCluster(args: GetClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cockroach:index/getCluster:getCluster", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCluster.
 */
export interface GetClusterArgs {
    id: string;
}

/**
 * A collection of values returned by getCluster.
 */
export interface GetClusterResult {
    readonly accountId: string;
    readonly backupConfig: outputs.GetClusterBackupConfig;
    readonly cloudProvider: string;
    readonly cockroachVersion: string;
    readonly creatorId: string;
    readonly customerCloudAccount: outputs.GetClusterCustomerCloudAccount;
    readonly dedicated: outputs.GetClusterDedicated;
    readonly deleteProtection: boolean;
    readonly fullVersion: string;
    readonly id: string;
    readonly labels: {[key: string]: string};
    readonly name: string;
    readonly operationStatus: string;
    readonly parentId: string;
    readonly plan: string;
    readonly regions: outputs.GetClusterRegion[];
    readonly serverless: outputs.GetClusterServerless;
    readonly state: string;
    readonly upgradeStatus: string;
}
/**
 * CockroachDB Cloud cluster. Can be Dedicated or Serverless.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const clusterId = config.require("clusterId");
 * const cockroach2 = cockroach.getCluster({
 *     id: clusterId,
 * });
 * ```
 */
export function getClusterOutput(args: GetClusterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cockroach:index/getCluster:getCluster", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCluster.
 */
export interface GetClusterOutputArgs {
    id: pulumi.Input<string>;
}
