// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Information about restore jobs on a specific cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Fetch the latest restore job
 * const latestRestore = cockroach.getRestores({
 *     clusterId: prodCluster.id,
 *     sortOrder: "DESC",
 *     limit: 1,
 * });
 * export const latestRestoreId = latestRestore.then(latestRestore => latestRestore.restores?.[0]?.id);
 * // Fetch restore jobs within a specific date range
 * const restoresInRange = cockroach.getRestores({
 *     clusterId: prodCluster.id,
 *     startTime: "2025-08-15",
 *     endTime: "2025-08-19",
 *     sortOrder: "DESC",
 *     limit: 5,
 * });
 * ```
 */
export function getRestores(args: GetRestoresArgs, opts?: pulumi.InvokeOptions): Promise<GetRestoresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cockroach:index/getRestores:getRestores", {
        "clusterId": args.clusterId,
        "endTime": args.endTime,
        "limit": args.limit,
        "sortOrder": args.sortOrder,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getRestores.
 */
export interface GetRestoresArgs {
    /**
     * The ID of the cluster where the restore jobs ran or are currently running.
     */
    clusterId: string;
    /**
     * Ending timestamp of the range (exclusive) used to search for restore jobs based on their creation time. If this field is provided, startTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    endTime?: string;
    /**
     * The maximum number of restore jobs to return. If not set, only the first 500 restore jobs will be returned.
     */
    limit?: number;
    /**
     * Specifies the sort direction for the returned results. Use `ASC` for ascending or `DESC` for descending order.
     */
    sortOrder?: string;
    /**
     * Beginning timestamp of the range (inclusive) used to search for restore jobs based on their creation time. If this field is provided, endTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    startTime?: string;
}

/**
 * A collection of values returned by getRestores.
 */
export interface GetRestoresResult {
    /**
     * The ID of the cluster where the restore jobs ran or are currently running.
     */
    readonly clusterId: string;
    /**
     * Ending timestamp of the range (exclusive) used to search for restore jobs based on their creation time. If this field is provided, startTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    readonly endTime?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The maximum number of restore jobs to return. If not set, only the first 500 restore jobs will be returned.
     */
    readonly limit?: number;
    readonly restores: outputs.GetRestoresRestore[];
    /**
     * Specifies the sort direction for the returned results. Use `ASC` for ascending or `DESC` for descending order.
     */
    readonly sortOrder?: string;
    /**
     * Beginning timestamp of the range (inclusive) used to search for restore jobs based on their creation time. If this field is provided, endTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    readonly startTime?: string;
}
/**
 * Information about restore jobs on a specific cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * // Fetch the latest restore job
 * const latestRestore = cockroach.getRestores({
 *     clusterId: prodCluster.id,
 *     sortOrder: "DESC",
 *     limit: 1,
 * });
 * export const latestRestoreId = latestRestore.then(latestRestore => latestRestore.restores?.[0]?.id);
 * // Fetch restore jobs within a specific date range
 * const restoresInRange = cockroach.getRestores({
 *     clusterId: prodCluster.id,
 *     startTime: "2025-08-15",
 *     endTime: "2025-08-19",
 *     sortOrder: "DESC",
 *     limit: 5,
 * });
 * ```
 */
export function getRestoresOutput(args: GetRestoresOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRestoresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cockroach:index/getRestores:getRestores", {
        "clusterId": args.clusterId,
        "endTime": args.endTime,
        "limit": args.limit,
        "sortOrder": args.sortOrder,
        "startTime": args.startTime,
    }, opts);
}

/**
 * A collection of arguments for invoking getRestores.
 */
export interface GetRestoresOutputArgs {
    /**
     * The ID of the cluster where the restore jobs ran or are currently running.
     */
    clusterId: pulumi.Input<string>;
    /**
     * Ending timestamp of the range (exclusive) used to search for restore jobs based on their creation time. If this field is provided, startTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    endTime?: pulumi.Input<string | undefined>;
    /**
     * The maximum number of restore jobs to return. If not set, only the first 500 restore jobs will be returned.
     */
    limit?: pulumi.Input<number | undefined>;
    /**
     * Specifies the sort direction for the returned results. Use `ASC` for ascending or `DESC` for descending order.
     */
    sortOrder?: pulumi.Input<string | undefined>;
    /**
     * Beginning timestamp of the range (inclusive) used to search for restore jobs based on their creation time. If this field is provided, endTime must also be included in the request. Uses a date format with optional timestamp, for example: `2023-01-15` or `2023-01-15T10:30:00Z`.
     */
    startTime?: pulumi.Input<string | undefined>;
}
