// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Log Export configuration for a cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const clusterId = config.require("clusterId");
 * const authPrincipal = config.require("authPrincipal");
 * const awsExternalId = config.require("awsExternalId");
 * const example = new cockroach.LogExportConfig("example", {
 *     logExportConfigId: clusterId,
 *     authPrincipal: authPrincipal,
 *     logName: "example",
 *     type: "GCP_CLOUD_LOGGING",
 *     redact: true,
 *     awsExternalId: awsExternalId,
 *     groups: [
 *         {
 *             logName: "sql",
 *             channels: [
 *                 "SQL_SCHEMA",
 *                 "SQL_EXEC",
 *             ],
 *             redact: false,
 *         },
 *         {
 *             logName: "devops",
 *             channels: [
 *                 "OPS",
 *                 "HEALTH",
 *                 "STORAGE",
 *             ],
 *             minLevel: "WARNING",
 *         },
 *     ],
 *     omittedChannels: ["SQL_PERF"],
 * });
 * ```
 *
 * ## Import
 *
 * format: <cluster id>
 *
 * ```sh
 * $ pulumi import cockroach:index/logExportConfig:LogExportConfig example 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class LogExportConfig extends pulumi.CustomResource {
    /**
     * Get an existing LogExportConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LogExportConfigState, opts?: pulumi.CustomResourceOptions): LogExportConfig {
        return new LogExportConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/logExportConfig:LogExportConfig';

    /**
     * Returns true if the given object is an instance of LogExportConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LogExportConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LogExportConfig.__pulumiType;
    }

    /**
     * Either the AWS Role ARN that identifies a role that the cluster account can assume to write to CloudWatch or the GCP Project ID that the cluster service account has permissions to write to for cloud logging.
     */
    declare public readonly authPrincipal: pulumi.Output<string>;
    /**
     * The external ID to use when assuming the AWS role.
     */
    declare public readonly awsExternalId: pulumi.Output<string | undefined>;
    /**
     * Indicates when log export was initially configured.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly groups: pulumi.Output<outputs.LogExportConfigGroup[] | undefined>;
    /**
     * Cluster ID.
     */
    declare public readonly logExportConfigId: pulumi.Output<string>;
    /**
     * An identifier for the logs in the customer's log sink.
     */
    declare public readonly logName: pulumi.Output<string>;
    /**
     * Controls what CRDB channels do not get exported.
     */
    declare public readonly omittedChannels: pulumi.Output<string[] | undefined>;
    /**
     * Controls whether logs are redacted before forwarding to customer sinks.
     */
    declare public readonly redact: pulumi.Output<boolean | undefined>;
    /**
     * Controls whether all logs are sent to a specific region in the customer sink.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * Encodes the possible states that a log export configuration can be in as it is created, deployed, and disabled.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The cloud selection being exported to along with the cloud logging platform. Possible values are:
     *   * AWS_CLOUDWATCH
     *   * GCP_CLOUD_LOGGING
     *   * AZURE_LOG_ANALYTICS
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Indicates when the log export configuration was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Elaborates on the log export status and hints at how to fix issues that may have occurred during asynchronous operations.
     */
    declare public /*out*/ readonly userMessage: pulumi.Output<string>;

    /**
     * Create a LogExportConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LogExportConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LogExportConfigArgs | LogExportConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LogExportConfigState | undefined;
            resourceInputs["authPrincipal"] = state?.authPrincipal;
            resourceInputs["awsExternalId"] = state?.awsExternalId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["groups"] = state?.groups;
            resourceInputs["logExportConfigId"] = state?.logExportConfigId;
            resourceInputs["logName"] = state?.logName;
            resourceInputs["omittedChannels"] = state?.omittedChannels;
            resourceInputs["redact"] = state?.redact;
            resourceInputs["region"] = state?.region;
            resourceInputs["status"] = state?.status;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["userMessage"] = state?.userMessage;
        } else {
            const args = argsOrState as LogExportConfigArgs | undefined;
            if (args?.authPrincipal === undefined && !opts.urn) {
                throw new Error("Missing required property 'authPrincipal'");
            }
            if (args?.logExportConfigId === undefined && !opts.urn) {
                throw new Error("Missing required property 'logExportConfigId'");
            }
            if (args?.logName === undefined && !opts.urn) {
                throw new Error("Missing required property 'logName'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["authPrincipal"] = args?.authPrincipal;
            resourceInputs["awsExternalId"] = args?.awsExternalId;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["logExportConfigId"] = args?.logExportConfigId;
            resourceInputs["logName"] = args?.logName;
            resourceInputs["omittedChannels"] = args?.omittedChannels;
            resourceInputs["redact"] = args?.redact;
            resourceInputs["region"] = args?.region;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["userMessage"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LogExportConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LogExportConfig resources.
 */
export interface LogExportConfigState {
    /**
     * Either the AWS Role ARN that identifies a role that the cluster account can assume to write to CloudWatch or the GCP Project ID that the cluster service account has permissions to write to for cloud logging.
     */
    authPrincipal?: pulumi.Input<string | undefined>;
    /**
     * The external ID to use when assuming the AWS role.
     */
    awsExternalId?: pulumi.Input<string | undefined>;
    /**
     * Indicates when log export was initially configured.
     */
    createdAt?: pulumi.Input<string | undefined>;
    groups?: pulumi.Input<pulumi.Input<inputs.LogExportConfigGroup>[] | undefined>;
    /**
     * Cluster ID.
     */
    logExportConfigId?: pulumi.Input<string | undefined>;
    /**
     * An identifier for the logs in the customer's log sink.
     */
    logName?: pulumi.Input<string | undefined>;
    /**
     * Controls what CRDB channels do not get exported.
     */
    omittedChannels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Controls whether logs are redacted before forwarding to customer sinks.
     */
    redact?: pulumi.Input<boolean | undefined>;
    /**
     * Controls whether all logs are sent to a specific region in the customer sink.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * Encodes the possible states that a log export configuration can be in as it is created, deployed, and disabled.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * The cloud selection being exported to along with the cloud logging platform. Possible values are:
     *   * AWS_CLOUDWATCH
     *   * GCP_CLOUD_LOGGING
     *   * AZURE_LOG_ANALYTICS
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Indicates when the log export configuration was last updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Elaborates on the log export status and hints at how to fix issues that may have occurred during asynchronous operations.
     */
    userMessage?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a LogExportConfig resource.
 */
export interface LogExportConfigArgs {
    /**
     * Either the AWS Role ARN that identifies a role that the cluster account can assume to write to CloudWatch or the GCP Project ID that the cluster service account has permissions to write to for cloud logging.
     */
    authPrincipal: pulumi.Input<string>;
    /**
     * The external ID to use when assuming the AWS role.
     */
    awsExternalId?: pulumi.Input<string | undefined>;
    groups?: pulumi.Input<pulumi.Input<inputs.LogExportConfigGroup>[] | undefined>;
    /**
     * Cluster ID.
     */
    logExportConfigId: pulumi.Input<string>;
    /**
     * An identifier for the logs in the customer's log sink.
     */
    logName: pulumi.Input<string>;
    /**
     * Controls what CRDB channels do not get exported.
     */
    omittedChannels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Controls whether logs are redacted before forwarding to customer sinks.
     */
    redact?: pulumi.Input<boolean | undefined>;
    /**
     * Controls whether all logs are sent to a specific region in the customer sink.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The cloud selection being exported to along with the cloud logging platform. Possible values are:
     *   * AWS_CLOUDWATCH
     *   * GCP_CLOUD_LOGGING
     *   * AZURE_LOG_ANALYTICS
     */
    type: pulumi.Input<string>;
}
