// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Physical replication stream.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const pcrExample1 = new cockroach.Cluster("pcr_example_1", {
 *     name: clusterName1,
 *     cloudProvider: cloudProvider,
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: Number(storageGib),
 *         numVirtualCpus: Number(numVirtualCpus),
 *         cidrRange: cidrRange1,
 *         supportsClusterVirtualization: true,
 *     },
 *     regions: .map(r => ({
 *         name: r,
 *         nodeCount: Number(clusterNodeCount),
 *     })),
 * });
 * const pcrExample2 = new cockroach.Cluster("pcr_example_2", {
 *     name: clusterName2,
 *     cloudProvider: cloudProvider,
 *     plan: "ADVANCED",
 *     dedicated: {
 *         storageGib: Number(storageGib),
 *         numVirtualCpus: Number(numVirtualCpus),
 *         cidrRange: cidrRange2,
 *         supportsClusterVirtualization: true,
 *     },
 *     regions: .map(r => ({
 *         name: r,
 *         nodeCount: Number(clusterNodeCount),
 *     })),
 * });
 * const pcrStream = new cockroach.PhysicalReplicationStream("pcr_stream", {
 *     primaryClusterId: pcrExample1.id,
 *     standbyClusterId: pcrExample2.id,
 * });
 * ```
 *
 * ## Import
 *
 * format: <physical replication stream id>
 *
 * ```sh
 * $ pulumi import cockroach:index/physicalReplicationStream:PhysicalReplicationStream my_stream 370c7f34-72e8-4238-b474-13767a579fb3
 * ```
 */
export class PhysicalReplicationStream extends pulumi.CustomResource {
    /**
     * Get an existing PhysicalReplicationStream resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PhysicalReplicationStreamState, opts?: pulumi.CustomResourceOptions): PhysicalReplicationStream {
        return new PhysicalReplicationStream(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/physicalReplicationStream:PhysicalReplicationStream';

    /**
     * Returns true if the given object is an instance of PhysicalReplicationStream.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PhysicalReplicationStream {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PhysicalReplicationStream.__pulumiType;
    }

    /**
     * The timestamp indicating the actual timestamp at which failover was finalized.
     */
    declare public /*out*/ readonly activatedAt: pulumi.Output<string>;
    /**
     * The timestamp at which the replication stream was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The timestamp at which to perform failover. If not specified, failover will occur at the latest consistent replicated time. Cannot be used with failover_immediately.
     */
    declare public readonly failoverAt: pulumi.Output<string | undefined>;
    /**
     * If true, failover will occur immediately at the latest consistent replicated time. Cannot be used with failover_at.
     */
    declare public readonly failoverImmediately: pulumi.Output<boolean | undefined>;
    /**
     * ID of the primary cluster, which is the replication source.
     */
    declare public readonly primaryClusterId: pulumi.Output<string>;
    /**
     * The timestamp indicating the point up to which data has been replicated.
     */
    declare public /*out*/ readonly replicatedTime: pulumi.Output<string>;
    /**
     * The replication lag in seconds.
     */
    declare public /*out*/ readonly replicationLagSeconds: pulumi.Output<number>;
    /**
     * The timestamp indicating the earliest time that the replication stream can failover to.
     */
    declare public /*out*/ readonly retainedTime: pulumi.Output<string>;
    /**
     * ID of the standby cluster, which is the replication target.
     */
    declare public readonly standbyClusterId: pulumi.Output<string>;
    /**
     * The status of the replication stream.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a PhysicalReplicationStream resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PhysicalReplicationStreamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PhysicalReplicationStreamArgs | PhysicalReplicationStreamState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PhysicalReplicationStreamState | undefined;
            resourceInputs["activatedAt"] = state?.activatedAt;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["failoverAt"] = state?.failoverAt;
            resourceInputs["failoverImmediately"] = state?.failoverImmediately;
            resourceInputs["primaryClusterId"] = state?.primaryClusterId;
            resourceInputs["replicatedTime"] = state?.replicatedTime;
            resourceInputs["replicationLagSeconds"] = state?.replicationLagSeconds;
            resourceInputs["retainedTime"] = state?.retainedTime;
            resourceInputs["standbyClusterId"] = state?.standbyClusterId;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as PhysicalReplicationStreamArgs | undefined;
            if (args?.primaryClusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'primaryClusterId'");
            }
            if (args?.standbyClusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'standbyClusterId'");
            }
            resourceInputs["failoverAt"] = args?.failoverAt;
            resourceInputs["failoverImmediately"] = args?.failoverImmediately;
            resourceInputs["primaryClusterId"] = args?.primaryClusterId;
            resourceInputs["standbyClusterId"] = args?.standbyClusterId;
            resourceInputs["activatedAt"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["replicatedTime"] = undefined /*out*/;
            resourceInputs["replicationLagSeconds"] = undefined /*out*/;
            resourceInputs["retainedTime"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PhysicalReplicationStream.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PhysicalReplicationStream resources.
 */
export interface PhysicalReplicationStreamState {
    /**
     * The timestamp indicating the actual timestamp at which failover was finalized.
     */
    activatedAt?: pulumi.Input<string | undefined>;
    /**
     * The timestamp at which the replication stream was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The timestamp at which to perform failover. If not specified, failover will occur at the latest consistent replicated time. Cannot be used with failover_immediately.
     */
    failoverAt?: pulumi.Input<string | undefined>;
    /**
     * If true, failover will occur immediately at the latest consistent replicated time. Cannot be used with failover_at.
     */
    failoverImmediately?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the primary cluster, which is the replication source.
     */
    primaryClusterId?: pulumi.Input<string | undefined>;
    /**
     * The timestamp indicating the point up to which data has been replicated.
     */
    replicatedTime?: pulumi.Input<string | undefined>;
    /**
     * The replication lag in seconds.
     */
    replicationLagSeconds?: pulumi.Input<number | undefined>;
    /**
     * The timestamp indicating the earliest time that the replication stream can failover to.
     */
    retainedTime?: pulumi.Input<string | undefined>;
    /**
     * ID of the standby cluster, which is the replication target.
     */
    standbyClusterId?: pulumi.Input<string | undefined>;
    /**
     * The status of the replication stream.
     */
    status?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a PhysicalReplicationStream resource.
 */
export interface PhysicalReplicationStreamArgs {
    /**
     * The timestamp at which to perform failover. If not specified, failover will occur at the latest consistent replicated time. Cannot be used with failover_immediately.
     */
    failoverAt?: pulumi.Input<string | undefined>;
    /**
     * If true, failover will occur immediately at the latest consistent replicated time. Cannot be used with failover_at.
     */
    failoverImmediately?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the primary cluster, which is the replication source.
     */
    primaryClusterId: pulumi.Input<string>;
    /**
     * ID of the standby cluster, which is the replication target.
     */
    standbyClusterId: pulumi.Input<string>;
}
