// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * CockroachDB Cloud restore. Used to start a restore job from a managed backup.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const clusterRestore = new cockroach.Restore("cluster_restore", {
 *     destinationClusterId: "12345678-1234-4123-8123-123456789abc",
 *     type: "CLUSTER",
 *     sourceClusterId: "22222222-2222-4222-8222-222222222222",
 * });
 * const databaseRestore = new cockroach.Restore("database_restore", {
 *     destinationClusterId: "12345678-1234-4123-8123-123456789abc",
 *     type: "DATABASE",
 *     sourceClusterId: "22222222-2222-4222-8222-222222222222",
 *     restoreOpts: {
 *         newDbName: "new_database",
 *         schemaOnly: true,
 *     },
 *     objects: [{
 *         database: "database1",
 *     }],
 * });
 * const tableRestore = new cockroach.Restore("table_restore", {
 *     destinationClusterId: "12345678-1234-4123-8123-123456789abc",
 *     type: "TABLE",
 *     backupId: "11111111-1111-4111-8111-111111111111",
 *     restoreOpts: {
 *         intoDb: "other_database",
 *         skipLocalitiesCheck: true,
 *         skipMissingForeignKeys: true,
 *         skipMissingSequences: true,
 *     },
 *     objects: [
 *         {
 *             database: "database1",
 *             schema: "schema1",
 *             tables: [
 *                 "table_a",
 *                 "table_b",
 *             ],
 *         },
 *         {
 *             database: "database2",
 *             schema: "schema2",
 *             tables: ["table_c"],
 *         },
 *     ],
 * });
 * ```
 */
export class Restore extends pulumi.CustomResource {
    /**
     * Get an existing Restore resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RestoreState, opts?: pulumi.CustomResourceOptions): Restore {
        return new Restore(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/restore:Restore';

    /**
     * Returns true if the given object is an instance of Restore.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Restore {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Restore.__pulumiType;
    }

    /**
     * The timestamp at which the backup data was captured.
     */
    declare public /*out*/ readonly backupEndTime: pulumi.Output<string>;
    /**
     * ID of the managed backup from which data will be restored. If this value is not set, the restore job uses the most recent available backup on the source cluster.
     */
    declare public readonly backupId: pulumi.Output<string>;
    /**
     * Error code from the restore job, only populated if it has failed.
     */
    declare public /*out*/ readonly clientErrorCode: pulumi.Output<number>;
    /**
     * Error message from the restore job, only populated if it has failed.
     */
    declare public /*out*/ readonly clientErrorMessage: pulumi.Output<string>;
    /**
     * The timestamp at which the restore job completed.
     */
    declare public /*out*/ readonly completedAt: pulumi.Output<string>;
    /**
     * Decimal value showing the percentage of the restore job that has been completed. Value ranges from 0 to 1.
     */
    declare public /*out*/ readonly completionPercent: pulumi.Output<number>;
    /**
     * The CockroachDB internal job ID for the restore job.
     */
    declare public /*out*/ readonly crdbJobId: pulumi.Output<string>;
    /**
     * The time at which the restore job was initiated.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * ID of the cluster where the backup will be restored.
     */
    declare public readonly destinationClusterId: pulumi.Output<string>;
    /**
     * The name of the cluster to which the restore is being applied.
     */
    declare public /*out*/ readonly destinationClusterName: pulumi.Output<string>;
    /**
     * The list of objects to restore. Required when the restore job type is `DATABASE` or `TABLE`.
     */
    declare public readonly objects: pulumi.Output<outputs.RestoreObject[] | undefined>;
    /**
     * Additional options controlling the behavior of the restore job.
     */
    declare public readonly restoreOpts: pulumi.Output<outputs.RestoreRestoreOpts | undefined>;
    /**
     * ID of the source cluster containing the managed backup to be restored.
     */
    declare public readonly sourceClusterId: pulumi.Output<string | undefined>;
    /**
     * The name of the cluster from which the backup was taken.
     */
    declare public /*out*/ readonly sourceClusterName: pulumi.Output<string>;
    /**
     * The current status of the restore job.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Type describes the scope of the restore job. When using a DATABASE or TABLE restore, additional details must be passed in the objects attribute. Allowed values are: `CLUSTER` or `DATABASE` or `TABLE`.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a Restore resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RestoreArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RestoreArgs | RestoreState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RestoreState | undefined;
            resourceInputs["backupEndTime"] = state?.backupEndTime;
            resourceInputs["backupId"] = state?.backupId;
            resourceInputs["clientErrorCode"] = state?.clientErrorCode;
            resourceInputs["clientErrorMessage"] = state?.clientErrorMessage;
            resourceInputs["completedAt"] = state?.completedAt;
            resourceInputs["completionPercent"] = state?.completionPercent;
            resourceInputs["crdbJobId"] = state?.crdbJobId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["destinationClusterId"] = state?.destinationClusterId;
            resourceInputs["destinationClusterName"] = state?.destinationClusterName;
            resourceInputs["objects"] = state?.objects;
            resourceInputs["restoreOpts"] = state?.restoreOpts;
            resourceInputs["sourceClusterId"] = state?.sourceClusterId;
            resourceInputs["sourceClusterName"] = state?.sourceClusterName;
            resourceInputs["status"] = state?.status;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as RestoreArgs | undefined;
            if (args?.destinationClusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'destinationClusterId'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["backupId"] = args?.backupId;
            resourceInputs["destinationClusterId"] = args?.destinationClusterId;
            resourceInputs["objects"] = args?.objects;
            resourceInputs["restoreOpts"] = args?.restoreOpts;
            resourceInputs["sourceClusterId"] = args?.sourceClusterId;
            resourceInputs["type"] = args?.type;
            resourceInputs["backupEndTime"] = undefined /*out*/;
            resourceInputs["clientErrorCode"] = undefined /*out*/;
            resourceInputs["clientErrorMessage"] = undefined /*out*/;
            resourceInputs["completedAt"] = undefined /*out*/;
            resourceInputs["completionPercent"] = undefined /*out*/;
            resourceInputs["crdbJobId"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["destinationClusterName"] = undefined /*out*/;
            resourceInputs["sourceClusterName"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Restore.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Restore resources.
 */
export interface RestoreState {
    /**
     * The timestamp at which the backup data was captured.
     */
    backupEndTime?: pulumi.Input<string | undefined>;
    /**
     * ID of the managed backup from which data will be restored. If this value is not set, the restore job uses the most recent available backup on the source cluster.
     */
    backupId?: pulumi.Input<string | undefined>;
    /**
     * Error code from the restore job, only populated if it has failed.
     */
    clientErrorCode?: pulumi.Input<number | undefined>;
    /**
     * Error message from the restore job, only populated if it has failed.
     */
    clientErrorMessage?: pulumi.Input<string | undefined>;
    /**
     * The timestamp at which the restore job completed.
     */
    completedAt?: pulumi.Input<string | undefined>;
    /**
     * Decimal value showing the percentage of the restore job that has been completed. Value ranges from 0 to 1.
     */
    completionPercent?: pulumi.Input<number | undefined>;
    /**
     * The CockroachDB internal job ID for the restore job.
     */
    crdbJobId?: pulumi.Input<string | undefined>;
    /**
     * The time at which the restore job was initiated.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * ID of the cluster where the backup will be restored.
     */
    destinationClusterId?: pulumi.Input<string | undefined>;
    /**
     * The name of the cluster to which the restore is being applied.
     */
    destinationClusterName?: pulumi.Input<string | undefined>;
    /**
     * The list of objects to restore. Required when the restore job type is `DATABASE` or `TABLE`.
     */
    objects?: pulumi.Input<pulumi.Input<inputs.RestoreObject>[] | undefined>;
    /**
     * Additional options controlling the behavior of the restore job.
     */
    restoreOpts?: pulumi.Input<inputs.RestoreRestoreOpts | undefined>;
    /**
     * ID of the source cluster containing the managed backup to be restored.
     */
    sourceClusterId?: pulumi.Input<string | undefined>;
    /**
     * The name of the cluster from which the backup was taken.
     */
    sourceClusterName?: pulumi.Input<string | undefined>;
    /**
     * The current status of the restore job.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Type describes the scope of the restore job. When using a DATABASE or TABLE restore, additional details must be passed in the objects attribute. Allowed values are: `CLUSTER` or `DATABASE` or `TABLE`.
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Restore resource.
 */
export interface RestoreArgs {
    /**
     * ID of the managed backup from which data will be restored. If this value is not set, the restore job uses the most recent available backup on the source cluster.
     */
    backupId?: pulumi.Input<string | undefined>;
    /**
     * ID of the cluster where the backup will be restored.
     */
    destinationClusterId: pulumi.Input<string>;
    /**
     * The list of objects to restore. Required when the restore job type is `DATABASE` or `TABLE`.
     */
    objects?: pulumi.Input<pulumi.Input<inputs.RestoreObject>[] | undefined>;
    /**
     * Additional options controlling the behavior of the restore job.
     */
    restoreOpts?: pulumi.Input<inputs.RestoreRestoreOpts | undefined>;
    /**
     * ID of the source cluster containing the managed backup to be restored.
     */
    sourceClusterId?: pulumi.Input<string | undefined>;
    /**
     * Type describes the scope of the restore job. When using a DATABASE or TABLE restore, additional details must be passed in the objects attribute. Allowed values are: `CLUSTER` or `DATABASE` or `TABLE`.
     */
    type: pulumi.Input<string>;
}
