// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * CockroachDB Cloud service account. A service account represents a non-person user. By default a service account has no access but it can be accompanied by either a cockroach.UserRoleGrants resource or any number of cockroach.UserRoleGrant resources to grant it roles.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const prodSa = new cockroach.ServiceAccount("prod_sa", {
 *     name: "Prod cluster SA",
 *     description: "A service account used for managing access to the prod cluster",
 * });
 * const prodSaUserRoleGrants = new cockroach.UserRoleGrants("prod_sa", {
 *     userId: prodSa.id,
 *     roles: [{
 *         roleName: "CLUSTER_ADMIN",
 *         resourceType: "CLUSTER",
 *         resourceId: prod.id,
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * format <resource> <service account id>
 *
 * ```sh
 * $ pulumi import cockroach:index/serviceAccount:ServiceAccount api_service_account 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class ServiceAccount extends pulumi.CustomResource {
    /**
     * Get an existing ServiceAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceAccountState, opts?: pulumi.CustomResourceOptions): ServiceAccount {
        return new ServiceAccount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/serviceAccount:ServiceAccount';

    /**
     * Returns true if the given object is an instance of ServiceAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceAccount.__pulumiType;
    }

    /**
     * Creation time of the service account.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Name of the creator of the service account.
     */
    declare public /*out*/ readonly creatorName: pulumi.Output<string>;
    /**
     * Description of the service account.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Name of the service account.
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a ServiceAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServiceAccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceAccountArgs | ServiceAccountState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceAccountState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["creatorName"] = state?.creatorName;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as ServiceAccountArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["creatorName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceAccount resources.
 */
export interface ServiceAccountState {
    /**
     * Creation time of the service account.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Name of the creator of the service account.
     */
    creatorName?: pulumi.Input<string | undefined>;
    /**
     * Description of the service account.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the service account.
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ServiceAccount resource.
 */
export interface ServiceAccountArgs {
    /**
     * Description of the service account.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the service account.
     */
    name?: pulumi.Input<string | undefined>;
}
