// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * CockroachDB SQL user.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const clusterId = config.require("clusterId");
 * const sqlUserPassword = config.require("sqlUserPassword");
 * const cockroach2 = new cockroach.SqlUser("cockroach", {
 *     name: "example-sql-user",
 *     passwordWo: sqlUserPassword,
 *     passwordWoVersion: 1,
 *     clusterId: clusterId,
 * });
 * ```
 *
 * ## Import
 *
 * format: <cluster id>:<sql user name>
 *
 * ```sh
 * $ pulumi import cockroach:index/sqlUser:SqlUser bill 1f69fdd2-600a-4cfc-a9ba-16995df0d77d:bill
 * ```
 */
export class SqlUser extends pulumi.CustomResource {
    /**
     * Get an existing SqlUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SqlUserState, opts?: pulumi.CustomResourceOptions): SqlUser {
        return new SqlUser(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/sqlUser:SqlUser';

    /**
     * Returns true if the given object is an instance of SqlUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SqlUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SqlUser.__pulumiType;
    }

    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * SQL user name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Deprecated. If provided, this field sets the password of the SQL user when created. The value is persisted in Terraform state, which is the reason for deprecation; prefer `passwordWo`. If omitted, a random password is generated and not saved to state. The password must be changed via the CockroachDB cloud console.
     *
     * @deprecated The `password` attribute persists the clear text password in state. Migrate to `passwordWo` (with `passwordWoVersion` for rotations): Pulumi keeps `passwordWo` only as an encrypted secret input and never in resource outputs or Terraform state. `password` will be removed in a future major release of the provider.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only password for the SQL user (Terraform CLI 1.11+ required). The value is sent on create and on rotation but never stored in Terraform state. To rotate, change the value and bump `passwordWoVersion`; without a version bump, Terraform cannot detect changes to a write-only attribute. Mutually exclusive with `password`.
     */
    declare public readonly passwordWo: pulumi.Output<string | undefined>;
    /**
     * Trigger attribute for rotating `passwordWo`. Increment this integer to force Terraform to re-apply the current `passwordWo` value. Only meaningful when `passwordWo` is set.
     */
    declare public readonly passwordWoVersion: pulumi.Output<number | undefined>;

    /**
     * Create a SqlUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SqlUserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SqlUserArgs | SqlUserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SqlUserState | undefined;
            resourceInputs["clusterId"] = state?.clusterId;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["passwordWo"] = state?.passwordWo;
            resourceInputs["passwordWoVersion"] = state?.passwordWoVersion;
        } else {
            const args = argsOrState as SqlUserArgs | undefined;
            if (args?.clusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterId'");
            }
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["passwordWo"] = args?.passwordWo ? pulumi.secret(args.passwordWo) : undefined;
            resourceInputs["passwordWoVersion"] = args?.passwordWoVersion;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "passwordWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SqlUser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SqlUser resources.
 */
export interface SqlUserState {
    clusterId?: pulumi.Input<string | undefined>;
    /**
     * SQL user name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Deprecated. If provided, this field sets the password of the SQL user when created. The value is persisted in Terraform state, which is the reason for deprecation; prefer `passwordWo`. If omitted, a random password is generated and not saved to state. The password must be changed via the CockroachDB cloud console.
     *
     * @deprecated The `password` attribute persists the clear text password in state. Migrate to `passwordWo` (with `passwordWoVersion` for rotations): Pulumi keeps `passwordWo` only as an encrypted secret input and never in resource outputs or Terraform state. `password` will be removed in a future major release of the provider.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only password for the SQL user (Terraform CLI 1.11+ required). The value is sent on create and on rotation but never stored in Terraform state. To rotate, change the value and bump `passwordWoVersion`; without a version bump, Terraform cannot detect changes to a write-only attribute. Mutually exclusive with `password`.
     */
    passwordWo?: pulumi.Input<string | undefined>;
    /**
     * Trigger attribute for rotating `passwordWo`. Increment this integer to force Terraform to re-apply the current `passwordWo` value. Only meaningful when `passwordWo` is set.
     */
    passwordWoVersion?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a SqlUser resource.
 */
export interface SqlUserArgs {
    clusterId: pulumi.Input<string>;
    /**
     * SQL user name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Deprecated. If provided, this field sets the password of the SQL user when created. The value is persisted in Terraform state, which is the reason for deprecation; prefer `passwordWo`. If omitted, a random password is generated and not saved to state. The password must be changed via the CockroachDB cloud console.
     *
     * @deprecated The `password` attribute persists the clear text password in state. Migrate to `passwordWo` (with `passwordWoVersion` for rotations): Pulumi keeps `passwordWo` only as an encrypted secret input and never in resource outputs or Terraform state. `password` will be removed in a future major release of the provider.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only password for the SQL user (Terraform CLI 1.11+ required). The value is sent on create and on rotation but never stored in Terraform state. To rotate, change the value and bump `passwordWoVersion`; without a version bump, Terraform cannot detect changes to a write-only attribute. Mutually exclusive with `password`.
     */
    passwordWo?: pulumi.Input<string | undefined>;
    /**
     * Trigger attribute for rotating `passwordWo`. Increment this integer to force Terraform to re-apply the current `passwordWo` value. Only meaningful when `passwordWo` is set.
     */
    passwordWoVersion?: pulumi.Input<number | undefined>;
}
