// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage all the role grants for a user. This resource is authoritative.  If role grants are added elsewhere, for example, via the console UI or another terraform project, using this resource will try to reset them. Use the cockroach.UserRoleGrant resource for non-authoritative role grants.  ORG_MEMBER is a required role and must be included.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const userId = config.require("userId");
 * const cockroach2 = new cockroach.UserRoleGrants("cockroach", {
 *     userId: userId,
 *     roles: [
 *         {
 *             roleName: "ORG_MEMBER",
 *             resourceType: "ORGANIZATION",
 *             resourceId: "",
 *         },
 *         {
 *             roleName: "ORG_ADMIN",
 *             resourceType: "ORGANIZATION",
 *             resourceId: "",
 *         },
 *         {
 *             roleName: "CLUSTER_ADMIN",
 *             resourceType: "CLUSTER",
 *             resourceId: prod.id,
 *         },
 *         {
 *             roleName: "FOLDER_ADMIN",
 *             resourceType: "FOLDER",
 *             resourceId: dev.id,
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * format: <user id>
 *
 * ```sh
 * $ pulumi import cockroach:index/userRoleGrants:UserRoleGrants service_account 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class UserRoleGrants extends pulumi.CustomResource {
    /**
     * Get an existing UserRoleGrants resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserRoleGrantsState, opts?: pulumi.CustomResourceOptions): UserRoleGrants {
        return new UserRoleGrants(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/userRoleGrants:UserRoleGrants';

    /**
     * Returns true if the given object is an instance of UserRoleGrants.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserRoleGrants {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserRoleGrants.__pulumiType;
    }

    /**
     * The list of roles to include. ORG_MEMBER must be included.
     */
    declare public readonly roles: pulumi.Output<outputs.UserRoleGrantsRole[]>;
    /**
     * ID of the user to grant these roles to.
     */
    declare public readonly userId: pulumi.Output<string>;

    /**
     * Create a UserRoleGrants resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserRoleGrantsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserRoleGrantsArgs | UserRoleGrantsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserRoleGrantsState | undefined;
            resourceInputs["roles"] = state?.roles;
            resourceInputs["userId"] = state?.userId;
        } else {
            const args = argsOrState as UserRoleGrantsArgs | undefined;
            if (args?.roles === undefined && !opts.urn) {
                throw new Error("Missing required property 'roles'");
            }
            if (args?.userId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["roles"] = args?.roles;
            resourceInputs["userId"] = args?.userId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UserRoleGrants.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UserRoleGrants resources.
 */
export interface UserRoleGrantsState {
    /**
     * The list of roles to include. ORG_MEMBER must be included.
     */
    roles?: pulumi.Input<pulumi.Input<inputs.UserRoleGrantsRole>[] | undefined>;
    /**
     * ID of the user to grant these roles to.
     */
    userId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a UserRoleGrants resource.
 */
export interface UserRoleGrantsArgs {
    /**
     * The list of roles to include. ORG_MEMBER must be included.
     */
    roles: pulumi.Input<pulumi.Input<inputs.UserRoleGrantsRole>[]>;
    /**
     * ID of the user to grant these roles to.
     */
    userId: pulumi.Input<string>;
}
