// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Configure minor version upgrade deferral for a cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cockroach from "@nellisauction/pulumi-cockroach";
 *
 * const config = new pulumi.Config();
 * const clusterId = config.require("clusterId");
 * const offsetDuration = config.get("offsetDuration") || "FIXED_DEFERRAL";
 * const example = new cockroach.VersionDeferral("example", {
 *     versionDeferralId: clusterId,
 *     deferralPolicy: offsetDuration,
 * });
 * ```
 *
 * ## Import
 *
 * format: <cluster id>
 *
 * ```sh
 * $ pulumi import cockroach:index/versionDeferral:VersionDeferral example 1f69fdd2-600a-4cfc-a9ba-16995df0d77d
 * ```
 */
export class VersionDeferral extends pulumi.CustomResource {
    /**
     * Get an existing VersionDeferral resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VersionDeferralState, opts?: pulumi.CustomResourceOptions): VersionDeferral {
        return new VersionDeferral(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroach:index/versionDeferral:VersionDeferral';

    /**
     * Returns true if the given object is an instance of VersionDeferral.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VersionDeferral {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VersionDeferral.__pulumiType;
    }

    /**
     * The policy for delaying automated patch version upgrades after their release.
     *   - Set to `DEFERRAL_30_DAYS` to defer each upgrade by 30 days.
     *   - Set to `DEFERRAL_60_DAYS` to defer each upgrade by 60 days.
     *   - Set to `DEFERRAL_90_DAYS` to defer each upgrade by 90 days.
     *   - Set to `NOT_DEFERRED` to apply each upgrade soon after the patch is released.
     */
    declare public readonly deferralPolicy: pulumi.Output<string>;
    /**
     * The earliest possible date and time for the next patch update, as calculated based on the configured `deferralPolicy`.
     * The next patch is applied after this deferral date and time in a maintenance window..
     */
    declare public /*out*/ readonly deferredUntil: pulumi.Output<string>;
    /**
     * Cluster ID.
     */
    declare public readonly versionDeferralId: pulumi.Output<string>;

    /**
     * Create a VersionDeferral resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VersionDeferralArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VersionDeferralArgs | VersionDeferralState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VersionDeferralState | undefined;
            resourceInputs["deferralPolicy"] = state?.deferralPolicy;
            resourceInputs["deferredUntil"] = state?.deferredUntil;
            resourceInputs["versionDeferralId"] = state?.versionDeferralId;
        } else {
            const args = argsOrState as VersionDeferralArgs | undefined;
            if (args?.deferralPolicy === undefined && !opts.urn) {
                throw new Error("Missing required property 'deferralPolicy'");
            }
            if (args?.versionDeferralId === undefined && !opts.urn) {
                throw new Error("Missing required property 'versionDeferralId'");
            }
            resourceInputs["deferralPolicy"] = args?.deferralPolicy;
            resourceInputs["versionDeferralId"] = args?.versionDeferralId;
            resourceInputs["deferredUntil"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VersionDeferral.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VersionDeferral resources.
 */
export interface VersionDeferralState {
    /**
     * The policy for delaying automated patch version upgrades after their release.
     *   - Set to `DEFERRAL_30_DAYS` to defer each upgrade by 30 days.
     *   - Set to `DEFERRAL_60_DAYS` to defer each upgrade by 60 days.
     *   - Set to `DEFERRAL_90_DAYS` to defer each upgrade by 90 days.
     *   - Set to `NOT_DEFERRED` to apply each upgrade soon after the patch is released.
     */
    deferralPolicy?: pulumi.Input<string | undefined>;
    /**
     * The earliest possible date and time for the next patch update, as calculated based on the configured `deferralPolicy`.
     * The next patch is applied after this deferral date and time in a maintenance window..
     */
    deferredUntil?: pulumi.Input<string | undefined>;
    /**
     * Cluster ID.
     */
    versionDeferralId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VersionDeferral resource.
 */
export interface VersionDeferralArgs {
    /**
     * The policy for delaying automated patch version upgrades after their release.
     *   - Set to `DEFERRAL_30_DAYS` to defer each upgrade by 30 days.
     *   - Set to `DEFERRAL_60_DAYS` to defer each upgrade by 60 days.
     *   - Set to `DEFERRAL_90_DAYS` to defer each upgrade by 90 days.
     *   - Set to `NOT_DEFERRED` to apply each upgrade soon after the patch is released.
     */
    deferralPolicy: pulumi.Input<string>;
    /**
     * Cluster ID.
     */
    versionDeferralId: pulumi.Input<string>;
}
